### ISSUE TITLE
long key support

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-c-client#121]
java-client 는 long key (32000) support 를 하고 있는 상태이고, c-client 도 이를 적용하기 위한 이슈이다.
변경이 필요한 부분은 key 저장 방식, command response 모듈이다.

**key 저장 방식**
- key string 저장 필드는 static array (250 size) 로 정의되어 있고, 이 필드는 result, collection_result 구조체에 들어있다. 
- result 구조체들은 memcached_st 구조체에 들어있어서, key array 크기를 늘리면 memcached_st 구조체 크기가 꽤 커진다.
- pool 을 구성할 경우 max_pool_size 만큼 memcached_st 가 생성될 것을 고려하면, 비효율적으로 메모리를 차지할 것이다.
- key 저장 방식을 value 와 같이 문자열 관리 구조체를 사용해서 malloc 하여 heap 에 저장하도록 변경하면 위 문제가 없지만,
  - key field type 변경이 필요해져서 응용 코드와 기존 c-client 코드 수정이 필요하다. (array -> struct // malloc, free)

**command request 모듈**
- key string 을 copy 없이 바로 io 수행하므로 key 크기와 상관없다.

**command response 모듈**
- key string 을 copy 하므로 static 버퍼의 크기는 key string 최대 길이에 맞게 늘려야 한다.
  - 키 제한을 2K ~ 4K 정도로 두면 버퍼의 크기를 늘리는 것으로 간단하게 해결된다.
  - 1MB 이상으로 둔다면 key string copy 없이 바로 result 구조체의 key field 에 저장하도록 처리 한다. (value 처리하듯)
    - value 와 다르게 key 는 사전에 길이를 알 수 없으므로, malloc & realloc(부족 시) 방식으로 처리 한다.

**Comment by SuhwanJang** [comment]
@jhpark816 
키 제한을 캐시 서버와 다르게 둘 지부터 결정을 해야할 것 같습니다. 이슈 내용에 대해 의견주시면 좋겠습니다.

**Comment by jhpark816** [comment]
@SuhwanJang @minkikim89 @hjyun328 
별도 offline 회의가 필요한 것 같습니다. 모임 요청해 주시죠.

**Comment by SuhwanJang** [comment]
최대 키 제한은 4K로 결정하였습니다. 이유는
- 응용 코드와 기존 c-client 코드의 수정을 최소화하기 위함.
- 대부분의 경우 키를 짧게 사용하며, 4K 이상 키를 사용하는 경우는 없을 것.

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-c-client/commit/743511ddfbaa6f424f8df598bba358cc2d0dff27
- 최대 키 제한 변경 (250 => 4K)
