### ISSUE TITLE
"CLEANUP: enable optimize mget operation with instance version" 리뷰와 수정

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#131]
[CLEANUP: enable optimize mget operation with instance version](https://github.com/naver/arcus-c-client/commit/8d34980fc58056fc15653d0b696add42838003bb) 커밋에 대한 리뷰 의견입니다.
이번에 다시 보니, 수정해야 할 큰 사항들이 보입니다.

첫째, 각 memcached server의 버전 정보를 얻는 방식에 관하여,
- 문제점
   - 기존 코드를 너무 많이 변경하고 있음.
   - 최신 libmemcached 코드와 차이가 많음.
-  최신 libmemcached 확인
   - 각 memcached server의 버전 정보를 구하는 기능이 이미 들어가 있음: memcached_version_instance()
   - version response 처리에서 version 정보 획득은 response 모듈에서 처리하고 있음.
   - memcached_version() 함수도 병렬 수행이 가능하게 최적화되어 있음.
- 수정 방안
   - 최신 libmemcached 구현 방안을 그대로 따르는 것이 나을 것 같음.
   - enterprise 버전 확인도 response 모듈에서 처리되어야 함.
   - mget 지원 여부의 설정은 외부에서 설정하는 것이 좋을 듯 하지만, 적절한 위치는 검토 필요.

둘째, mget 연산의 최적화 처리
- 문제점
   - 기존 get, gets, mget 처리 코드가 1개 함수 내에 모두 들어가다 보니, 복잡해 짐.
- 수정 방안
   - 기존 get, gets 연산은 기존 함수로 처리하고
   - mget 연산이면 별도 구현된 mget 함수를 호출하여 처리하면 나을 듯.
- 추가 확인해야 할 사항
   - gets 연산도 mget 처리하여도 되지 않나 ?
   - cache server와 java client에서 gets 연산의 처리 방식 확인 필요.
   - get vs. mget 판단 기준: 현재는 2개 이상의 key이면 mget
      - N개 이상의 key 조건이면서, 어떤 N값이 좋은 지를 판단 및 근거 제시

**Comment by SuhwanJang** [comment]
commit : https://github.com/naver/arcus-c-client/commit/29b396dc95b4dfe785aaf501c56120147d214c7e
- version 관련해서는 이슈 코멘트대로 처리

commit : https://github.com/naver/arcus-c-client/commit/223babbf39217651f646eeb95bd580229d202c4f
- 명령 처리(single/multiple) 관점에서 get 과 mget 분리
- 새로 추가된 mget 은 기존 memcached_mget() API 사용.
- mget 지원하는 버전이면, key 개수 관계없이 mget 사용. 

mgets 개발은 https://github.com/naver/arcus-memcached/issues/540 에서 진행
