### ISSUE TITLE
io_flush() 에서 poll timeout 발생에 대한 처리 검토

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-c-client#146]
c-client 는 synchronous io 방식이기 때문에 write 시에 timeout 발생은 
한번에 socket buffer 를 넘는 command 를 보내지 않는 이상 발생할 확률이 거의 없겠지만, 
code 안전성을 높이기 위해 handling 하도록 하고, 관련해서 아래 사항을 검토한다.

- single line command(set, get ..) 와 multi line command(mget) 에서 command string 일부만 보내진 상황에서
  - 남은 write length 가 io write buffer 를 넘어서는 경우
  - timeout 이 발생하여 이전에 send 된 데이터와 증가된 response count 로 인한 이슈

최종적으로는 timeout 발생 시에 send 한 데이터 유무에 관계없이 connection 을 다시 맺도록 해주는 것이 가장 나아 보여 delayed reconnect 처리할 것으로 생각된다.

**Comment by SuhwanJang** [comment]
io buffer 보다 2배 이상 큰 write_length 을 write 하는 경우를 가정하고,
이 때에 동작과 timeout handling 관련된 내용 서술합니다.
- io buffer full 이 된 경우 flush 한 후 남은 write_length 를 write. (write_length == 0 까지 반복)
- io flush 이후 다음 flush 에서 timeout 에러가 발생하면,
  - write() 호출한 쪽은 성공 리턴 값을 받지 못하면 response count 를 증가시키지 않음. (모든 연산 동일. response count 이슈 없음.)
  - server 는 terminated character(\r\n) 를 받지 못하여 남은 command string 기다리는 상황.
    => reconnect 하지 않으면, other command write 때 실패하게 될 것임.

따라서 timeout 발생 시 reconnect 가 필요하고, reconnect 방식은 비정상적인 상황에 대한 recovery time 을 두기 위해 delayed 방식으로 수행.

**Comment by SuhwanJang** [comment]
@jhpark816 
다른 이견 없으시면 위에서 설명한대로
io_flush() 에서 poll timeout 발생 시 delayed reconnect 하도록 PR 보내겠습니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
OK. 그렇게 해 주세요.

**Comment by SuhwanJang** [comment]
commit : https://github.com/naver/arcus-c-client/commit/9abd841f8444c8d90dba2c0931341ce6c280c878
io_flush() 에서 poll timeout 발생 시 memcached_quit_server() 을 호출하도록 수정하였습니다.
