### ISSUE TITLE
switchover peer 못 찾을 시에 handling 검토

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-c-client#169]
삼중화 기능이 추가됨에 따라 SWITCHOVER/REPL_SLAVE 응답에 switchover peer 정보가 포함되는데,
어떤 문제로 인해 memcached_rgroup_switchover() 에서 peer 정보를 찾지 못하여도
do_action 으로 goto 되어 계속 요청을 보내게 됩니다. 
memcached_rgroup_switchover() 에서 peer 정보를 찾지 못하면 에러 메세지 출력 및 -1 를 리턴하고, 
이 경우에 SWITCHOVER or REPL_SLAVE 에러코드를 응용에 리턴해주는 것이 안전해보입니다.
```
 #ifdef ENABLE_REPLICATION
 do_action:
 #endif
   /* Send command header */
   rc= memcached_vdo(instance, vector, 6, to_write);

   if (rc == MEMCACHED_SUCCESS)
   {
     if (to_write == false)
     {
       rc= MEMCACHED_BUFFERED;
     }
     else if (ptr->flags.no_reply or ptr->flags.piped)
     {
       rc= MEMCACHED_SUCCESS;
     }
     else
     {
       char result[MEMCACHED_DEFAULT_COMMAND_SIZE];
       rc= memcached_coll_response(instance, result, MEMCACHED_DEFAULT_COMMAND_SIZE, NULL);
 #ifdef ENABLE_REPLICATION
       if (rc == MEMCACHED_SWITCHOVER or rc == MEMCACHED_REPL_SLAVE)
       {
         ZOO_LOG_INFO(("Switchover: hostname=%s port=%d error=%s",
                       instance->hostname, instance->port, memcached_strerror(ptr, rc)));
         memcached_rgroup_switchover(ptr, instance);
         instance= memcached_server_instance_fetch(ptr, server_key);
         goto do_action;
       }
 #endif
       memcached_set_last_response_code(ptr, rc);
```

**Comment by SuhwanJang** [comment]
memcached_rgroup_switchover() 에서 server list 정보를 업데이트하지 못하더라도 cache list 가 바뀌면 zk thread 에 의해서 업데이트 되므로 다음 memcached_server_instance_fetch() 에서 master 노드를 얻어올 수 있게 됩니다.
그런데, 간혹 switchover N번 중에 한번은 repl_slave 응답이 무한정 오는 경우를 확인하였는데, 이에 대해 확인해볼 예정입니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
본 이슈는 직접 확인 후에 close 하겠습니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
코드를 다시 검토해보니 cache list update 후 pool repopulate 작업 수행하더라도 연산 수행 중인 memcached_st 구조체는
arcus_server_check_for_update() 를 처음 이후에는 수행하지 않기 때문에 변경된 노드 목록이 반영되지 않은 상태라서 이슈에 기술한 문제가 발생할 것으로 보입니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
memcached_rgroup_switchover()는 true or false를 리턴하고,
호출하는 쪽은 아래 코드가 되어야 할 것 같습니다.
즉, switchover 실패 시에는 retry하지 않고 어떤 오류(??)를 설정해야 할 것 같습니다.

```
       char result[MEMCACHED_DEFAULT_COMMAND_SIZE];
       rc= memcached_coll_response(instance, result, MEMCACHED_DEFAULT_COMMAND_SIZE, NULL);
 #ifdef ENABLE_REPLICATION
       if (rc == MEMCACHED_SWITCHOVER or rc == MEMCACHED_REPL_SLAVE)
       {
         ZOO_LOG_INFO(("Switchover: hostname=%s port=%d error=%s",
                       instance->hostname, instance->port, memcached_strerror(ptr, rc)));
         if (memcached_rgroup_switchover(ptr, instance) == true) {
             instance= memcached_server_instance_fetch(ptr, server_key);
             goto do_action;
         }
         rc= XXXX; /* set error */
       }
 #endif
```

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-c-client/commit/da366d9cd9c4c264a37931c3f0d05b6a2e16fb14
