### ISSUE TITLE
pipe 연산에서 실패 처리 검토

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-c-client#174]
pipe 연산에서 실패 처리를 구현하려면, 먼저 응용에서 pipe API 사용 방식 정의가 필요합니다.

응용은 pipe API 사용에 대한 응답(rc)으로 성공(MEMCACHED_SUCCESS) or 실패(MEMCACHED_WRITE_FAILURE or 
MEMCACHED_REPL_SLAVE .. ) 받게 됩니다.
 
```
// lop pipe insert
rc= memcached_lop_piped_insert(memc, key, strlen(key),
                               MEMCACHED_COLL_MAX_PIPED_CMD_SIZE,
                               indexes, values, valueslen,
                               &attributes, responses, &piped_rc);
```

응용이 확인할 인자는 responses ( 각각의 연산에 대한 응답을 담은 배열 : STORED or EXISTS ) 와 piped_rc ( pipe aggregation 결과 : ALL_SUCCESS or ALL_FAILURE ) 이고, rc 가 성공이면 확인할 것이고 실패면 확인하지 않을 것 입니다. 기존 구현은 이와 같이 사용할 것으로 보고 실패 시에 responses 와 piped_rc 에 정확한 값을 넣어주지 않습니다.

하지만 실패로 응답한 경우에도 실제로는 일부 연산 요청이 서버에 반영될 수 있기 때문에 응용은 이에 대한 사실을 확인하고 싶을 수 있습니다.
이 경우에 piped_rc 에는 MEMCACHED_SOME_SUCCESS 넣고 responses 에는 성공한 요청들은 STORED 를 나머지 요청들은 실패 에러 코드를 넣어주어야 합니다.

기존 구현으로 유지하여도 무방하지 않나 생각합니다. 이유는 대부분의 응용은 실패 시에 아래와 같이 동작할 가능성이 높아 보입니다.
- responses 와 piped_rc 를 확인하지 않거나
- pipe 연산 요청을 재수행

**Comment by jhpark816** [comment]
먼저, rc 값으로 어떤 값들이 리턴되는 지를 확인해 보시죠.
- MEMCACHED_WRITE_FAILURE 경우는 요청 자체를 보내지 못한 상태이므로, responses, piped_rc를 설정할 수 없게 됩니다.
- 실패에 해당하는 rc는 모두 이 경우에 해당되지 않나 생각됩니다.

일부는 성공한 상태에서 REPL_SLAVE 오류가 나와서 나머지 연산을 수행하지 못한 경우 
- 최종 결과는 성공으로 리턴하고,
- responses와 piped_rc 값을 설정하여 제공하는 것이 맞다고 봅니다.

**Comment by SuhwanJang** [comment]
실패 시 리턴될 수 있는 에러 코드는 
- io read 실패 시 : MEMCACHED_CONNECTION_FAILURE, MEMCACHED_IN_PROGRESS
- 서버와 클라이언트 protocol 차이 : MEMCACHED_PARTIAL_READ, MEMCACHED_UNKNOWN_READ_FAILURE

이며, 일부 응답을 받고 발생할 수도 있습니다.
이 경우들은 요청은 정상적으로 보낸 것이므로 에러 코드 구분 없이 REPL_SLAVE 와 같이 처리하면 되지 않나 싶습니다.

**Comment by SuhwanJang** [comment]
최종 결과를 성공으로 리턴하는 것은 일부는 성공하였을 때만인 것이죠?
즉, 첫 번째 연산부터 REPL_SLAVE 오류가 나와서 전체 연산을 수행하지 못한 경우라면 오류를(REPL_SLAVE) 그대로 리턴해야 할 지

**Comment by SuhwanJang** [comment]
참고로 REPL_SLAVE 의 경우 내부적으로 요청을 다시 보냅니다. 그대로 리턴하는 경우는 switchover peer 를 찾지 못하였을 때입니다.
이 경우와 그 밖에 실패 에러들 모두 발생 가능성이 희박합니다. 정말 예외적인 경우들이므로 실패 에러 코드만 리턴해주고 응용은 재수행하도록 가이드하여도 충분하지 않나 생각됩니다.

**Comment by SuhwanJang** [comment]
unexpected error (switchover peer 찾지 못한 경우 or MEMCACHED_PARTIAL_READ 등 ..) 에 대한 처리를 어떻게 하면 좋을 지까지 논의를 하였습니다.

https://github.com/naver/arcus-c-client/blob/master/libmemcached/response.cc#L1422
질문 주셨던 개별 연산에서 실패(SERVER_ERROR out of memory)나면, aggregate 에러 코드는 SOME_SUCCESS 와 같이 에러 코드로 설정됩니다.

unexpected error 처리 방식에 대한 제 의견은 responses와 piped_rc 값을 설정하지 않고 에러 코드 그대로 리턴하여 끝내고, 응용은 issue report 하여 근본적인 문제를 찾아 해결하도록 하는 것이 안전하고 합리적이지 않나 생각합니다.

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-c-client/commit/e2e03eb27b8ef007e7ef80c422ea0b9023189b0d

pipe 연산에서 실패가 발생한 경우에도 rc, piped_rc, responses 에 아래와 같이 응용이 확인하여 처리하기 위해 적절한 값으로 설정하도록 수정하였습니다.

- rc
  - single instance 연산 : SUCCESS or 발생한 에러
  - bulk 연산 : SUCCESS or SOME_ERRORS(일부 성공) or FAILURE(전체 실패)
- piped_rc
  - ALL_SUCCESS : 전체 성공
  - ALL_FAILURE : 전체 실패
  - SOME_SUCCESS : 일부 성공
- responses
  - response 알 수 없는 연산의 경우 MEMCACHED_MAXIMUM_RETURN 로 설정
