### ISSUE TITLE
last response code 설정 검토

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-c-client#179]
last response code 설정은 `coll delete` 과 같이 성공 결과가 여러 개(DELETED or DELETED_DROP) 인 연산에 한에서만 해주는 것이 의미 있어 보입니다. 아래 `coll delete` 코드를 보면, 응용은 rc (SUCCESS) 만으로 collection item 제거되었는 지 여부를 알 수 없습니다.
- do_coll_delete()
```
   rc=  memcached_vdo(instance, vector, veclen, to_write);

   if (rc == MEMCACHED_SUCCESS)
   {
..
       char result[MEMCACHED_DEFAULT_COMMAND_SIZE];
       rc= memcached_coll_response(instance, result, MEMCACHED_DEFAULT_COMMAND_SIZE, NULL);
 #ifdef ENABLE_REPLICATION
       if (rc == MEMCACHED_SWITCHOVER or rc == MEMCACHED_REPL_SLAVE)
       {
         ZOO_LOG_INFO(("Switchover: hostname=%s port=%d error=%s",
                       instance->hostname, instance->port, memcached_strerror(ptr, rc)));
         if (memcached_rgroup_switchover(ptr, instance) == true) {
           instance= memcached_server_instance_fetch(ptr, server_key);
           goto do_action;
         }
       }
 #endif
       memcached_set_last_response_code(ptr, rc);

       if (rc == MEMCACHED_DELETED or
           rc == MEMCACHED_DELETED_DROPPED)
       {
         rc= MEMCACHED_SUCCESS;
       }
     }
   }
   return rc;
```

아래 연산들의 경우는 설정할 필요가 없음.
- rc(SUCCESS) 와 결과가 1:1 관계인 경우 
  - 일부 collection 연산 (ex. `coll create` - SUCCESS 는 CREATED 를 의미)
  - kv 연산
  - 기타 연산(flush, stats, version, dump ..)
- 다른 방식으로 알 수 있는 경우
  - pipe 연산의 경우 인자에 responses 를 통해 알 수 있음.

**Comment by jhpark816** [comment]
@SuhwanJang 
의견에 동의합니다.
rc 값으로 최종 상태를 알 수 없는 경우에 한하여 last response code를 설정하도록 합시다.

**Comment by jhpark816** [comment]
@SuhwanJang 
PR 코드를 보니, 논의 사항이 있습니다.
- pipe 연산에서는 last response code가 의미가 없어 제거하여도 될 것 같습니다.
- 그 외의 single 연산에서
   - response code가 ENGINE_SUCCESS로 변경되는 경우는 last response code를 남겨두는 것이 좋을 것 같습니다.

응용 입장에서 보면,
- 어떤 경우는 last response code가 설정되어 있고 다른 경우는 garbage 값이 들어가 있게 됩니다.
- 모든 경우에 last response code를 설정해 두는 것이 일관적이지 않을 까 하는 생각이 듭니다.

어떻게 생각하나요?

**Comment by SuhwanJang** [comment]
@jhpark816 
last response code 를 확인할 필요가 없는 연산에서 설정하는 것은 의미가 없어 보입니다. 
응용 코드에서도 모든 연산에서 last response code 확인하지 않을 것입니다. 만약 응용이 이를 확인하려면 연산 별로 성공에 대한 각 코드를 모두 알고 있어야 하는데, 효율성과 유지보수 측면에서 모두 좋지 않으므로 그러한 형태로 구현하지는 않을 겁니다. 만약 이렇게 구현한 응용이 있다고 가정하면 기존에 last response code 를 설정하지 않는 연산들이 있었으므로 이슈 문의가 있었을 겁니다.
따라서 last response code 필드의 본래 용도를 살려서 필요한 곳에서만 설정하는 것이 헷갈리지 않아 좋을 듯 합니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
하나만 더 질문하면,
기존에 single 연산에서 response code가 ENGINE_SUCCESS로 변경되는 경우 last response code를 남겨두었는 데,
이번에 이를 제거한다면 혹시 backward compatibility 문제가 발생할 가능성이 있을까요?

**Comment by SuhwanJang** [comment]
@jhpark816 
응용이 일부 연산만 last response code 확인하는 것은 이상하므로 문제 발생할 가능성은 거의 없을 것 같은데
안전하게 간다면 pipe 연산 제외하고 기존에 설정하는 곳만 남겨두면 될 것 같습니다.

**Comment by jhpark816** [comment]
@SuhwanJang 

아래는 c client 가이드 문서입니다. 예제 코드를 확인해 보시고 의견 주시기 바랍니다.
https://github.com/naver/arcus-c-client/blob/master/docs/05-set-API.md#set-element-%EC%A1%B4%EC%9E%AC-%EC%97%AC%EB%B6%80-%ED%99%95%EC%9D%B8

**Comment by jhpark816** [comment]
@SuhwanJang 
last response code 관련하여 전체 document를 확인해 볼 필요가 있습니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
가이드 문서의 예제 코드를 보니 rc(SUCCESS) 와 결과가 1:1 관계인 연산 중에서도 last response code 확인을 일관적으로 하지 않고 있네요.
- bop create 시에는 rc & last response code 확인, bop count 시에는 rc 만 확인.

어쨌든 가이드 문서에 last response code 확인 코드가 있으므로 기존에 설정했던 연산에서는 남겨두는 것이 안전하겠습니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
전체 document 확인해 본 후 최종 의견 드립니다.
- 아래 연산들은 다른 방식으로 최종 상태를 확인 가능하고, 기존 가이드 문서에도 조회하지 않으므로 설정 x. 
  - kv 연산
  - 일부 btree 연산 (bop count, bop incr/decr, bop position)
  - 기타 연산 (attr, flush, dump, version ..)
  - pipe 연산
- 이 외 연산들은 최종 상태 확인을 위해 필요하거나 backward compatibility 문제 방지 위해 설정
  - 위 btree 연산 3개를 제외한 모든 collection 연산 (coll create, coll insert/upsert, coll get, coll delete ...)

**Comment by jhpark816** [comment]
@SuhwanJang 
reasonable 합니다. 그렇게 PR 수정하시죠.

**Comment by SuhwanJang** [comment]
commit : https://github.com/naver/arcus-c-client/commit/c8fc60aea1e5e9d827e3b1594864c3d33bcb7b9b
https://github.com/naver/arcus-c-client/issues/179#issuecomment-984405301 와 같이 수정하였습니다.
