### ISSUE TITLE
Connection pool에서 timedout connection 객체들의 관리 개선

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#184]
- 현재 상태와 문제점
   - Connection pool에서 connection 객체들은 모두 stack 형식으로 관리한다.
      - 응용이 connection pool에서 connection 객체를 stack top에서 fetch하여 사용하고, stack top으로 반환한다.
   - 정상 상태의 connection 객체는 stack top으로 반환하여 다음 요청에 재사용하는 것이 좋다.
   - Timedout 상태의 connection 객체를 stack top으로 반환하면 다음 문제가 발생한다.
      - stack top에 있으므로 다시 응용이 fetch하여 사용할 가능성이 높다.
      - 다음 reconnect 시간이 되기 전까지는 "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" 오류를 발생시킨다.
      - 결국, timeout 상태의 connection 객체가 stack top에 존재함으로써 "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" 오류가 연속하여 발생하는 패턴을 보인다.
- 개선 방안
   - Timedout 상태의 connection 객체를 stack bottom으로 반환할 수 있다.
     - 불필요하게 많은 connection 객체가 캐시 노드와 실제 연결을 맺는 상태가 된다.
     - 요청이 많아짐에 따라 실제 연결을 맺는 connection 객체 수를 최소화하려는 원래 구현 의도와 달라지는 이슈가 있다.
   - Timeout 상태의 connction 객체를 따로 관리하는 reconnect queue를 두어 이용한다.
     - Timeout 상태의 connection 객체가 reconnect time이 되면, 응용에서 fetch할 수 있게 한다.
     - 응용에서 사용을 마친 connection 객체를 반환할 경우 connection 객체 상태에 따라 stack or reconnect queue에 둔다.
- 참고 사항
   - Timeout conection 객체이더라도, 그 connection 객체를 통해 실제 timeout 발생한 캐시 노드는 1개일 수 있으며, 다른 캐시 노드에 대한 연결은 정상일 수 있다. 이러한 상태를 고려한다.
   - C Client에서의 "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" 오류는 java client에서 "inactive node" 오류와 같은 성격이며, java client에서는 connection pool에서 connection 객체를 random 선택한다.

**Comment by jhpark816** [comment]
@SuhwanJang 
개선 방안의 design을 먼저 공유 바랍니다.

**Comment by jhpark816** [comment]
@SuhwanJang @uhm0311 
- mc 구조체에 있는 last_disconnected_server 관련 코드가 정확한 지를 확인해 주시고요.
- `last_disconnected_server->state != TIMEOUT_STATE` 이면, state는 어떤 값을 가지나요?
   - 위 코멘트를 정확히 리뷰하기 위해, state 값의 의미에 알고 있어야 할 것 같습니다.
   - 참고로, state 무관하게 동일하게 처리해야 할 것으로 보입니다.
- `mc_reconnect_pool` 보다 `mc_reconnect_queue` 라는 이름을 사용하시죠.
- 내가 생각하는 mc fetch scheduling 방식 (**검토 필요**)
   - mc_reconnect_queue is empty이면, mc_pool에서 mc fetch
   - mc_reconnect_queue is not empty이면, 
      - mc_pool에 이미 사용된 mc가 있으면 이를 fetch
      - mc_reconnect_queue에서 mc fetch (reconnect time이 되지 않더라도)

**Comment by uhm0311** [comment]
@jhpark816 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/server.h#L51-L57

코드를 분석해 보았는데, 다음과 같은 `server->state`는 다음과 같이 변화하는 것으로 보입니다.

![1](https://user-images.githubusercontent.com/51937838/148335554-420bf9b6-a8ab-4d59-9919-5fb05ec6a06e.png)

**Comment by SuhwanJang** [comment]
@jhpark816 @uhm0311 
> last_disconnected_server->state != TIMEOUT_STATE 이면, state는 어떤 값을 가지나요? 

state 전이도는 @uhm0311 님이 달아준 위 코멘트 보시면 되고,
TIMEOUT_STATE 가 아닌 경우면 성공적으로 서버와 연결하였음을 의미하는 CONNECTED 입니다. 
state 는 최종적으로 TIMEOUT or CONNECTED 둘 중 하나로 설정됩니다.

```
 memcached_return_t memcached_connect(memcached_server_write_instance_st server)
 {
...
   if (memcached_failed(rc= backoff_handling(server, in_timeout)))
   {
     set_last_disconnected_host(server);
     return rc;
   }

   /* We need to clean up the multi startup piece */
   switch (server->type)
   {
   case MEMCACHED_CONNECTION_UDP:
   case MEMCACHED_CONNECTION_TCP:
     rc= network_connect(server);
...
   }

   if (memcached_success(rc))
   {
     memcached_mark_server_as_clean(server);
     rc= memcached_version_instance(server);
     return rc;
   }

   set_last_disconnected_host(server);
   if (memcached_has_current_error(*server))
   {
     memcached_mark_server_for_timeout(server);
     assert(memcached_failed(memcached_server_error_return(server)));
   }
   else
   {
     memcached_set_error(*server, rc, MEMCACHED_AT);
     memcached_mark_server_for_timeout(server);
   }
...

   return rc;
 }
```

- network_connect() 결과가 success 이면, CONNECTED 상태
- failure 이면, CONNECTED 가 아닌 상태들을 갖을 수 있으나 memcached_mark_server_for_timeout() 에서 TIMEDOUT 상태로 설정

```
 static inline void memcached_mark_server_for_timeout(memcached_server_write_instance_st server)
 {
   if (server->state != MEMCACHED_SERVER_STATE_IN_TIMEOUT)
   {
     struct timeval next_time;
     if (server->root->retry_timeout != 0 and gettimeofday(&next_time, NULL) == 0)
     {
       server->next_retry= next_time.tv_sec +server->root->retry_timeout;
     }
     else
     {
       server->next_retry= 1; // Setting the value to 1 causes the timeout to occur immediatly
     }
 #ifdef IMMEDIATELY_RECONNECT
     if (server->immediate_reconnect)
     {
       server->next_retry= 1; // Setting the value to 1 causes the timeout to occur immediately
       server->immediate_reconnect= false;
     }
 #endif

     server->state= MEMCACHED_SERVER_STATE_IN_TIMEOUT;
     if (server->server_failure_counter_query_id != server->root->query_id)
     {
       server->server_failure_counter++;
       server->server_failure_counter_query_id= server->root->query_id;
     }
     set_last_disconnected_host(server);
   }
 }
```

**Comment by SuhwanJang** [comment]
@uhm0311 
기존 코드 기준으로 last_disconnected_server 관련 코드들이 정확한 지를 검토 부탁드립니다.
문제가 있을 수도 있고 없을 수도 있는데 한번 확인은 필요할 것 같아 요청드립니다.

**Comment by uhm0311** [comment]
@SuhwanJang 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/connect.cc#L615-L621

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/connect.cc#L553-L604

566 라인에서 `flags.auto_eject_hosts == true`이면 `last_disconnected_server`는 set 되는데 `TIMEOUT` 상태는 아니게 되지 않나요?

**Comment by SuhwanJang** [comment]
@uhm0311 
TIMEOUT 상태가 될 때만 `server_failure_counter` 를 증가시키므로 저 때는 이미 TIMEOUT 상태입니다.

**Comment by jhpark816** [comment]
@SuhwanJang @uhm0311 
`last_disconnected_server->state`는 항상 IN_TIMEOUT 상태인 것 같고, CONNECTED 상태는 없는 것 같습니다. 맞나요?

**Comment by uhm0311** [comment]
@jhpark816 

- 네 맞습니다.
- `last_disconnected_server`가 set 된 이후 다시 `last_disconnected_server`를 `NULL`로 초기화 하는 로직이 내부적으로 존재하지 않아 `last_disconnected_server`가 set 된 `mc`를 `mc_reconnect_queue`에서 `mc_pool`로 옮기기 위해서는 해당 `mc`가 연결 가능한지 확인하는 로직이 필요해 보입니다.
- `arcus-c-client`가 연결한 zookeeper에 memcached 노드가 2개 이상 있을 때, 하나라도 TIMEOUT이 되면 해당 노드의 정보가 `last_disconnected_server`에 set 되어 `mc_reconnect_queue`로 옮겨질 것입니다. 이러한 사항도 의도하는 바인지 궁금합니다.

**Comment by jhpark816** [comment]
@uhm0311 
- `last_disconnected_server`는 말 그대로 가장 최근에 disconnected server 정보를 보관해 두는 역할밖에 없습니다.
- `last_disconnected_server`와 무관하게 `mc_reconnect_queue` 구현해야 할 것 같습니다.

@SuhwanJang 
- `last_disconnected_server` 상태는 항상 IN_TIMEOUT 상태이므로, `mc_reconnect_queue` 이용 방식을 다시 정리해 보시죠.
- `last_disconnected_server`와 무관한 방식이어야 하지 않나 생각됩니다.

**Comment by SuhwanJang** [comment]
@jhpark816 @uhm0311 
`last_disconnected_server`는 항상 IN_TIMEOUT 상태이네요. 다시 정리하였습니다.

- connection 객체 상태 판단 방법
  - 기존 connection 객체에 있는 `last_disconnected_server` 를 통해 판단. 해당 값이 NULL 이 아니면 Timeout 상태, NULL 이면 정상 상태 (단, 내부적으로 timeout 상태에서 정상 상태로 되었을 때 `last_disconnected_server` reset 처리가 필요함)
 
- 정상 상태의 connection 객체를 빠르게 fetch 할 수 있도록 timeout list 는 queue (FIFO) 로 관리
  - queue 로 관리하기 위한 추가 필드 필요 ( front, rear )
  - `memcached_pool_st` 구조체에 `mc_reconnect_queue` 필드를 두고, `mc_pool` 과 동일한 시점에 같은 크기로 memory allocation 
 
- mc fetch scheduling 방식
 - `mc_reconnect_pool` is empty 이면, `mc_pool` 에서 fetch.
 - `mc_reconnect_pool` is not empty 이면,
   - `mc_pool` 에 이미 사용한 mc 있으면 이를 fetch
     - 이미 사용하였는 지에 대한 판단은 mc_pool 에 마지막 사용한 mc 위치를 가리키는 `used` 필드 추가하여 이용
     - `used` 는 처음에 `top` 과 같은 값이고, fetch 할 때마다 감소하여 0 으로 수렴. release 시에는 해당 mc 의 ketama version 이 master 와 달라서 free 하는 경우에만 증가. (참고로 mc_pool 은 stack)
   - `used` 지점에 mc 없으면 `mc_reconnect_pool` 에서 mc fetch 시도 
       - `last_disconnected_server` 의 reconnect time 확인하여 (`next_retry` 필드와 현재 시간 비교)
         - reconnect time 지났다면 `last_disconnected_server` reset 후 사용
         - 지나지 않았다면 `mc_pool` 에 `used` 이후에 mc 를 사용. (응용에서 timeout error 를 겪지 않게 하기 위함)
 - 만약 mc_pool empty 이고, `mc_reconnect_pool` is full 이면, (pool size 작은 경우 발생할 수 있음)
   - 어쩔 수 없이 `mc_reconnect_pool` 에서 mc fetch 하여 사용. => 응용은 timeout error 를 보고 network 등 원인 파악 필요  

`last_disconnected_server` 를 기존 용도로 두기 위해 이와 무관한 방식으로 구현한다면 
`memcached_st` 에 `last_reconnect_time` 필드를 두고 가장 최근에 timeout 발생한 서버에 재연결 가능한 시간을 설정해두어 사용.
- `next_retry` 설정과 동일한 시점에 설정 
- 해당 값이 0 이 아니면 Timeout 상태, 0 이면 정상 상태
- 정상 상태로 바뀌는 경우에 0으로 초기화해주어야 함.

**Comment by jhpark816** [comment]
@uhm0311 
memcached pool에 `mc_reconnect_queue`를 두고 mc fetch & push 기능을 잘 관리함으로써
응용에서 mc 사용 시의 오류를 최소화하는 방안을 정리해 볼 수 있을까요?

**Comment by jhpark816** [comment]
@uhm0311 
설계를 정리해 주시죠.

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

1. memcached_st 구조체에 멤버변수 `uint64_t last_disconnected_time`을 추가합니다. 초기값은 0입니다.
2. memcached_pool_st 구조체에 멤버변수 `memcached_st **mc_reconnect_queue`를 추가합니다. 원형 큐로 활용하기 위해 멤버변수 `uint32_t mc_reconnect_front`, `uint32_t mc_reconnect_rear`를 함께 추가합니다.
3. pool_create() 함수 호출 시 mc_reconnect_queue를 pool->max_size 크기의 배열로 메모리를 할당합니다.
4. set_last_disconnected_host() 함수에서 gettimeofday() 함수를 이용해 mc->last_disconnected_time을 현재 시간으로 정합니다.
5. pool_push() 함수에서 released_mc->last_disconnected_time 값이
    1. 0이면 기존 동작을 수행합니다.
    2. 0 보다 크면 pool->mc_pool 대신 pool->mc_reconnect_queue에 넣습니다. pool->top을 증가시키지 않습니다.
6. pool_fetch() 함수에서
    1. pool->mc_pool이 not empty이면 기존 동작을 수행합니다.
    2. pool->mc_pool이 empty이고
        1. pool->mc_reconnect_queue가 empty이면 기존 동작을 수행합니다.
        2. pool->mc_reconnect_queue가 not empty이면 아래와 같은 동작을 수행합니다.
            ```cxx
            timeval current_time;
            gettimeofday(&current_time, NULL);

            memcached_st *mc_reconnect = NULL;

            do 
            {
              mc_reconnect = pool->mc_reconnect_queue[pool->mc_reconnect_front];

              if (mc_reconnect->last_disconnected_time + mc_reconnect->retry_timeout < current_time.tv_sec) 
              {
                rc = MEMCACHED_SUCCESS;
                mc_reconnect->last_disconnected_time = 0;
                /* pool->mc_reconnect_front와 pool->mc_reconnect_rear의 값을 적절히 조정 */
                break;
              }
              else
              {
                mc_reconnect = NULL;

                if (relative_time.tv_sec == 0 and relative_time.tv_nsec == 0)
                {
                  rc = MEMCACHED_NOTFOUND;
                  break;
                }

                struct timespec time_to_wait= {0, 0};
                time_to_wait.tv_sec= time(NULL) +relative_time.tv_sec;
                time_to_wait.tv_nsec= relative_time.tv_nsec;

                int thread_ret;
                if ((thread_ret= pthread_cond_timedwait(&cond, &mutex, &time_to_wait)) != 0)
                {
                  if (thread_ret == ETIMEDOUT)
                  {
                    rc= MEMCACHED_TIMEOUT;
                  }
                  else
                  {
                    errno= thread_ret;
                    rc= MEMCACHED_ERRNO;
                  }
                  break;
                }
              }
            } while (mc_reconect == NULL);

            return mc_reconnect;
            ```

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

- 설계 개선 방안입니다.

6. pool_fetch() 함수에서
    1.  pool->mc_reconnect_queue가 not empty이고, `memcached_st *mc_reconnect = pool->mc_reconnect_queue[pool->mc_reconnect_front]` 일 때
        1.  `mc_reconnect->last_disconnected_time + mc_reconnect->retry_timeout <= current_time.tv_sec` 이면 mc_reconnect를 return 합니다.
        2.  그렇지 않은 경우
            1. pool->mc_pool이 not empty이면 기존 동작을 수행합니다.
            2. pool->mc_pool이 empty이면
                1. mc_pool_size < max_pool_size이면 기존 동작을 수행합니다.
                2. mc_pool_size == max_pool_size일 때
                    1. `mc_reconnect->last_disconnected_time + mc_reconnect->retry_timeout <= current_time.tv_sec` 이면 mc_reconnect를 return 합니다.
                    2. 그렇지 않은 경우 기존 동작에서 relative_time 동안 기다린 뒤
                        1. `mc_reconnect->last_disconnected_time + mc_reconnect->retry_timeout <= current_time.tv_sec` 이면 mc_reconnect를 return 합니다.
                        2. 그렇지 않은 경우 기존 동작을 수행합니다.
    2. pool->mc_reconnect_queue가 empty이면 기존 동작을 수행합니다.

**Comment by jhpark816** [comment]
@uhm0311 
아래와 같이 설정되었다고 가정합니다. (이상한 부분이 있지만)
- max work threads: 256
- pool init size: 512
- pool max size: 1024

이 상황에서 connection 맺고 있는 member mc 수가 256 이하임이 보장되나요?

**Comment by uhm0311** [comment]
@jhpark816 

> max work threads: 256
pool init size: 512
pool max size: 1024

- 해당 조건에 대하여
  1. grow_pool() 함수가 호출되지 않게 하기 위해서는 pool_fetch() 함수에서 다음과 같은 순서로 return 합니다.
      - reconnect time 조건을 만족하는 mc_reconnect
      - connected member mc
      - reconnect time 조건을 만족하지 않는 mc_reconnect
        - 이 때 reconnect time 조건을 만족하지 않는 mc_reconnect가 return될 경우 SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY 오류가 발생 할 수 있습니다.
  2. grow_pool() 함수가 호출될 수 있도록 하되, connected member mc의 수를 늘리지 않는 방안도 생각해보았습니다.
      - pool_push() 함수에서 pool->mc_reconnect_queue에 들어가는 released_mc의 connection을 끊습니다.
        - 이는 connected member mc의 개수가 max work threads 이하라는 점만 보장하는 방법으로, 서버 연결 시도 횟수는 max work threads를 넘습니다.

**Comment by jhpark816** [comment]
@uhm0311 
코멘트 합니다.
- `reconnect time 조건을 만족하지 않는 mc_reconnect` 리턴 시에 reconnect time 강제 조정하여 reconnect 시도하도록 처리
   - clean mc 리턴하여도 connect 할 것이므로, reconnect time 강제 조정이 나은 방법입니다.
   - 위에서 released_mc의 connection 강제 종료는 의미가 없습니다.
- 추가적으로 
   - 위의 connected member mc 식별은
       top 포인터 외에 한번도 사용된 적이 없는 member mc를 가리키는 clean 포인터를 두면 될 것 같습니다.

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

- commit: https://github.com/naver/arcus-c-client/commit/203217d71ebd7c43e25897f7fcbc920e94fe9982
- 위 commit 기준으로 member mc 관리에 변경사항이 생겼습니다. 다시 설계 방안 공유해 드립니다.

1. memcached_st 구조체에 멤버변수 `uint64_t last_disconnected_time`을 추가합니다. 초기값은 0입니다.
2. set_last_disconnected_host() 함수에서 gettimeofday() 함수를 이용해 mc->last_disconnected_time을 현재 시간으로 정합니다.
3. pool_push() 함수에서 released_mc->last_disconnected_time 값이
    1. 0이면 used_mc_head에 추가합니다.
    2. 0이 아니면 used_mc_tail에 추가합니다.
4. pool_fetch() 함수에서 fetched_mc->last_disconnected_time 값이
    1. 0이면 기존 동작을 수행합니다.
    2. 0이 아니고
        1. reconnect time 조건을 만족하면 fetched_mc->last_disconnected_time = 0으로 바꾼 뒤 return 합니다.
        2. reconnect time 조건을 만족하지 않으면 fetched_mc->servers 혹은 fetched_mc->rgroups를 순회하며 reconnect time 조건을 만족하도록 next_retry = 0으로 바꾸고 fetched_mc->last_disconnected_time = 0으로 바꾼 뒤 return 합니다.

**Comment by jhpark816** [comment]
@uhm0311 

먼저 질문이 있습니다.
- disconnected server가 있다는 사실만 표현하는 flag 방식이나 disconnected server count 정보도 가능할 것입니다.
   last_disconnected_time 의미의 필드가 가장 적합한가요?

위 수정 방식에서
- pool_push()에서 tail 추가하는 경우에 last_disconected_time 값을 미리 0으로 초기화하는 것이 좋겠습니다.
- 이미 tail 위치에 추가하여 일정 시간을 지나가도록 하였기 때문에
  mc fetch하면 무조건 reconnect 시도하게 만들려는 것입니다.
  따라서, pool 사용 시에는 push 시에 reconnect 설정을 모두 clear하면 좋겠습니다.
- standalone mc 사용할 경우, 응용이 무한정 reconnect try할 수 있습니다.
  이 경우를 대비하여, 기존 reconnect time 매커니즘은 그대로 유지되어야 하고요.
  기존 pool은 stack 동작이었기 때문에 마찬가지로 reconnect time 매커니즘이 필요했습니다.

**Comment by uhm0311** [comment]
@jhpark816 

> last_disconnected_time 의미의 필드가 가장 적합한가요?

- is_disconnected 필드와 같이 disconnected 여부만을 확인하는 경우 reconnect time 조건을 만족하는지 아닌지 확인할 수 없습니다.
- reconnect time 조건을 만족하는 경우에는 그대로 반환하면 다시 연결 시도를 합니다.
- reconnect time 조건을 만족하지 않는 경우에 그냥 반환하면 연결 시도를 하지 않고 항상 SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY 에러가 발생합니다. 

> reconnect time 조건을 만족하지 않으면 fetched_mc->servers 혹은 fetched_mc->rgroups를 순회하며 reconnect time 조건을 만족하도록 next_retry = 0으로 바꾸고 fetched_mc->last_disconnected_time = 0으로 바꾼 뒤 return 합니다.

- 따라서 그냥 반환하지 않고 위와 같은 작업을 수행한 뒤 반환해야 다시 연결 시도를 합니다.
- 이 때 last_disconnected_time 필드를 사용하지 않으면 reconnect time 조건을 만족하는지 아닌지 확인할 수 없으므로, is_disconnected = true이면 항상 mc->servers 혹은 mc->rgroups를 순회해야 합니다.
- last_disconnected_time 필드의 사용이 mc->servers 혹은 mc->rgroups를 항상 순회하지 않아도 되도록 만들 수 있는 쉬운 방법이라고 생각합니다.

> pool_push()에서 tail 추가하는 경우에 last_disconected_time 값을 미리 0으로 초기화하는 것이 좋겠습니다.

- pool_push() 시점에서는 reconnect time 조건을 만족하지 않을 확률이 높습니다. 따라서 대부분의 released_mc에 대하여 servers 혹은 rgroups를 순회해야 합니다.

> 이미 tail 위치에 추가하여 일정 시간을 지나가도록 하였기 때문에

- 언급하신 것 처럼 pool_fetch() 시점에서는 reconnect time 조건을 만족할 확률이 높습니다. 따라서 적은 수의 fetched_mc에 대하여 servers 혹은 rgroups를 순회하면 됩니다. 값을 늦게 초기화하는 것으로 순회를 적게 할 수 있다면 늦게 초기화 하는 것이 효율적이라고 생각합니다.

**Comment by jhpark816** [comment]
@uhm0311 
OK. fetch 시에 clear 합시다.
나머지는 PR 코드를 보고 논의해야 할 것 같습니다.

**Comment by SuhwanJang** [comment]
본 이슈 재검토한 결과 기존 방식을 유지하기로 하여 close 합니다.

last_disconnect_time 초기화 & timed-out mc 는 used_mc_list 의 tail 에 넣음으로써
- next fetch 시에 head mc 를 이용하여 retry 를 바로 할 수 있음.

하지만, recovery time 이 필요한 에러(network ..)가 발생한 서버에 요청 (connect or connected 상태라면 request) 은 실패할 가능성이 높음.
  - 여기서 발생할 수 있는 문제는 request 시에 실패하면 connection 을 끊는데, next mc 를 연달아 fetch 해가며 connection 을 끊음.
  - 일정 시간 뒤에 네트워크 정상화로 문제가 없어지면 connection 을 다시 맺어야 함.(비효율적)
  - libmemcached 원작자가 위의 이유를 고려하여 stack 으로 구현하였나?

추가로 기존에 delayed reconnect 기능이 있는데 pool 쪽에서 이것을 활용하지 않으면 해당 기능이 있는 의미도 없어짐.
- 만약에 본 방안을 넣는다면, 항상 immediate reconnect 하도록 하고 head 에 넣는 것이 더 맞는 구현으로 보임.
​
