### ISSUE TITLE
multi_threaded 샘플 코드 수정

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-c-client#186]
arcus 디렉토리에 있는 multi_threaded.c 를 보면
arcus_pool_connect() 실패 시에 global_mc 를 memcached_pool_push() 하고 종료하는데 이 로직이 맞는 지 검토 후 수정 바랍니다.
```
 int
 main(int argc __attribute__((unused)), char** argv __attribute__((unused)))
 {
   int x;
   int min_thread = 5;
   int max_thread = NUMBER_OF_THREADS;
   pthread_t tid[NUMBER_OF_THREADS];
   pthread_t tstat;

   memcached_pool_st *pool = NULL;

   global_mc = memcached_create(NULL);
   pool = memcached_pool_create(global_mc, min_thread, max_thread);

   if (!pool) {
     fprintf(stderr, "memcached_pool_create failed\n");
     return 1;
   }

   arcus_return_t arc = arcus_pool_connect(pool, zkadmin_addr, service_code);

   if (arc != ARCUS_SUCCESS) {
     fprintf(stderr, "arcus_connect() failed, reason=%s\n", arcus_strerror(arc));
     memcached_pool_push(pool, global_mc); // 검토 
     return 1;
   }

   signal(SIGINT, sig_handler);

   pthread_create(&tstat, NULL, my_statistics_thread, NULL);

   for (x=0; x<NUMBER_OF_THREADS; x++) {
     pthread_create(&tid[x], NULL, my_application_thread, pool);
   }

   for (x=0; x<NUMBER_OF_THREADS; x++) {
     pthread_join(tid[x], NULL);
   }

   release_resources(global_mc, pool);

   return 1;
 }
```

**Comment by SuhwanJang** [comment]
@uhm0311 multi_threaded.c 코드 참고하여 pool 사용 코드들을 봐두면 다른 pool 관련 이슈 처리에 도움이 될 것 같습니다.

**Comment by jhpark816** [comment]
@uhm0311 
추가 수정 사항이 있습니다.
- release_resources() 함수를 별도로 두지 않도록 고치시죠. 즉, resource 해제 작업을 main에서 바로 합시다.
- 리턴 값 확인하고, 수정 필요한 것 같습니다.
- 오류 핸들링을 정확하게 하시죠.

**Comment by uhm0311** [comment]
commit: https://github.com/naver/arcus-c-client/commit/e326a3327bcd810943fe58b9097a857679ccafcd

- https://github.com/naver/arcus-c-client/issues/186#issue-1089138396 `arcus_pool_connect()` 함수 실패 시 처리를 제거하고 `arcus_pool_connect()` 함수 성공 시 `arcus_pool_close()` 함수 호출하도록 변경했습니다. 
- https://github.com/naver/arcus-c-client/issues/186#issuecomment-1001501924 수정 사항 반영했습니다.
