### ISSUE TITLE
memcached_behavior_set_distribution() 함수 내부 버그 이슈

### ISSUE THREAD

**Issue by uhm0311** [naver/arcus-c-client#199]
https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/behavior.cc#L475-L492

해당 코드의 479 라인에서 `if (MEMCACHED_DISTRIBUTION_CONSISTENT_WEIGHTED)`는 항상 `true`입니다. `type` 변수와 `MEMCACHED_DISTRIBUTION_CONSISTENT_WEIGHTED` 상수를 비교하려는 것을 실수한 걸로 보입니다.

**Comment by jhpark816** [comment]
실수가 아닌 의도적으로 ketama.weighted = true 설정한 것으로 보입니다.
따라서, ketama.weighted 관련 코드 전체를 보고 수정 방안을 판단해야 합니다.

**Comment by ing-eoking** [comment]
해당 이슈 종료하겠습니다.
