### ISSUE TITLE
hashkit_get_function_test() 함수 내부 버그 이슈

### ISSUE THREAD

**Issue by uhm0311** [naver/arcus-c-client#200]
https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/tests/hashkit_functions.cc#L450-L467

해당 코드의 455 라인에서 `if (HASHKIT_HASH_CUSTOM)`는 항상 `true`입니다. `algo` 변수와 `HASHKIT_HASH_CUSTOM` 상수를 비교하려는 것을 실수한 것으로 보입니다.

**Comment by jhpark816** [comment]
@uhm0311 
test 의도를 확인하고, 그 의미에 맞게 수정해 보시죠.

**Comment by uhm0311** [comment]
@jhpark816 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/tests/hashkit_functions.cc#L450-L467

459 라인에서 `libhashkit_has_algorithm()` 함수의 결과가 `true`일 때 461~462 라인의 `hashkit_set_function()` 함수의 결과가 `HASHKIT_SUCCESS`로 나타나야 합니다. 그런데 `algo` 변수의 값이 `HASHKIT_HASH_CUSTOM`과 같을 때는 `libhashkit_has_algorithm()` 함수의 결과가 `true`이어도 `hashkit_set_function()` 함수의 결과가 `HASHKIT_SUCCESS`로 나타나지 않습니다. 따라서 다음과 같이 수정하는 방안을 검토해 보았습니다. 해당 방안 검토 부탁드립니다.

```cpp
static test_return_t hashkit_get_function_test(hashkit_st *hashk)
{
  for (int algo= int(HASHKIT_HASH_DEFAULT); algo < int(HASHKIT_HASH_MAX); algo++)
  {
    if (algo == int(HASHKIT_HASH_CUSTOM)) // 수정한 코드
      continue;
    /*
    if (HASHKIT_HASH_CUSTOM) // 기존 코드
    {
      continue;
    }
    */
    test_skip(true, libhashkit_has_algorithm(static_cast<hashkit_hash_algorithm_t>(algo)));

    test_compare(HASHKIT_SUCCESS,
                 hashkit_set_function(hashk, static_cast<hashkit_hash_algorithm_t>(algo)));

    test_compare(hashkit_get_function(hashk), algo);
  }
  return TEST_SUCCESS;
}
```

**Comment by jhpark816** [comment]
@uhm0311 
현재 "if (HASHKIT_HASH_CUSTOM) continue;"하는 코드는 test 자체를 수행하지 않게 합니다.

아래와 같이 수정하여 test 시에 실패하지 않도록 하시죠.
- HASHKIT_HASH_CUSTOM 경우는 skip 하는 것이 맞습니다.
- libhashkit_has_algorithm()가 false 리턴하면, test_skip()은 현재 test 전체를 skip 합니다.
  따라서, skip해야 하는 경우가 있는 지도 봐 주시고, 정상인 경우만 test하게 하시죠.

**Comment by uhm0311** [comment]
> skip해야 하는 경우가 있는 지도 봐 주시고, 정상인 경우만 test하게 하시죠.

- 아래와 같은 수정 방안을 검토해 보았습니다. `hashkit_get_function()` 함수를 테스트 하는 것이기 때문에 `libhashkit_has_algorithm()` 함수에서 `false`가 반환 되었을 때는 `hashkit_set_function()` 함수가 적절한 해시 함수를 set 해주지 않을 것이므로 skip 하는 것으로 판단했습니다. 검토 부탁드립니다.

```cxx
static test_return_t hashkit_get_function_test(hashkit_st *hashk)
{
  for (int algo= int(HASHKIT_HASH_DEFAULT); algo < int(HASHKIT_HASH_MAX); algo++)
  {
    if (algo == int(HASHKIT_HASH_CUSTOM))
      continue;

    if (libhashkit_has_algorithm(static_cast<hashkit_hash_algorithm_t>(algo)))
    {
      test_compare(HASHKIT_SUCCESS,
                   hashkit_set_function(hashk, static_cast<hashkit_hash_algorithm_t>(algo)));

      test_compare(hashkit_get_function(hashk), algo);
    }
  }
  return TEST_SUCCESS;
}
```

**Comment by jhpark816** [comment]
@uhm0311 
위와 같이 수정합시다.
uni testing 결과 확인해 주시고요.

**Comment by uhm0311** [comment]
@jhpark816 
unit test 결과 정상적으로 나왔습니다. PR 올리겠습니다.

**Comment by uhm0311** [comment]
commit: https://github.com/naver/arcus-c-client/commit/d84737698a06ef735b3f2cd9a40497bbdbc9d524

https://github.com/naver/arcus-c-client/issues/200#issuecomment-1005404103
위 방안으로 수정했습니다.
