### ISSUE TITLE
MacOS 환경에서 arcus_proxy_create() 함수가 실패하는 현상

### ISSUE THREAD

**Issue by uhm0311** [naver/arcus-c-client#206]
https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L285-L327

- `arcus_proxy_create()` 함수 안에서 위의 함수를 호출합니다.
- MacOS 환경에서 295 ~ 300 라인을 실행할 때, CentOS 환경이 아니므로 `TARGET_OS_LINUX`가 정의되어 있지 않고, 따라서 299 ~ 300 라인이 실행됩니다.
- 그 결과 MacOS 환경에서는 errno=9 (Bad file descriptor) 오류가 발생합니다.
- CentOS 환경에서는 정상적으로 동작하는 것을 확인했습니다.
- `TARGET_OS_LINUX`는 `m4/pandora_platform.m4` 파일에서 정의해주고 있는데, 이 파일을 참고하여 295 라인을 `#if defined(TARGET_OS_LINUX) || defined(TARGET_OS_OSX)`로 변경했을 때 MacOS 환경에서도 정상적으로 동작했습니다.
- MacOS 환경과 CentOS 환경에서 `man mmap`을 실행하면, file descriptor를 -1로 사용하기 위해서는 `MAP_ANONYMOUS` 플래그를 줘야 한다고 명시되어 있습니다.
- 다음은 MacOS 환경에서 관련된 내용입니다.

```
     MAP_ANONYMOUS     Synonym for MAP_ANON.

     MAP_ANON          Map anonymous memory not associated with any specific file.  The offset argument is ignored.  Mac OS X specific: the file descriptor used for creating MAP_ANON regions can be used to pass some Mach VM flags, and can be
                       specified as -1 if no such flags are associated with the region.  Mach VM flags are defined in <mach/vm_statistics.h> and the ones that currently apply to mmap are:

                       VM_FLAGS_PURGABLE   to create Mach purgable (i.e. volatile) memory.

                       VM_MAKE_TAG(tag)    to associate an 8-bit tag with the region.
                       <mach/vm_statistics.h> defines some preset tags (with a VM_MEMORY_ prefix).  Users are encouraged to use tags between 240 and 255.  Tags are used by tools such as vmmap(1) to help identify specific memory regions.

```

- 다음은 CentOS 환경에서 관련된 내용입니다.

```
       MAP_ANONYMOUS
              The mapping is not backed by any file; its contents are initialized to zero.  The fd and offset arguments are ignored; however, some implementations require fd to be -1 if MAP_ANONYMOUS (or MAP_ANON) is specified, and portable applications should ensure this.  The use of MAP_ANONYMOUS in conjunction with MAP_SHARED is supported on Linux
              only since kernel 2.4.
```

**Comment by jhpark816** [comment]
@uhm0311 
- MacOS 버전에 따라 다를 것 같습니다.
  - MAP_ANONYMOUS defined 버전
  - MAP_ANON defined 버전
  - 둘 다 defined 되지 않은 버전이 있을라나?
- 어떻게 처리하면 좋은가요?
  -  검토 바랍니다.

처리 방안 중의 하나는 아래와 같이 MAP_ANONYMOUS를 define하면 될 것 같습니다.

```
#if !defined(MAP_ANONYMOUS)
  #if defined(MAP_ANON)
    #define MAP_ANONYMOUS MAP_ANON
  #else
    #define MAP_ANONYMOUS 0
  #endif
#endif
```

**Comment by uhm0311** [comment]
@jhpark816 
- 조사 결과 MacOS 환경에서는 [`MAP_ANON`가 먼저 정의](https://github.com/apple/darwin-xnu/blob/3eaa6b2cf6d66cebc3974fffeb31fc70175aa59b/bsd/sys/mman.h) 되었고 그 이후 [버전이 올라가면서 `MAP_ANONYMOUS`가 추가](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/mman.h) 되었습니다.

> 어떻게 처리하면 좋은가요?

- `TARGET_OS_OSX`가 정의 되었을 때에도 `MAP_ANONYMOUS` 플래그를 사용해야 하니, MacOS 환경에서의 [`mman.h`](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/mman.h) 파일을 참고하여 아래와 같이 처리하는 방안을 검토해 보았습니다.

```cxx
#if defined(TARGET_OS_LINUX) || defined(TARGET_OS_OSX)
  #ifdef TARGET_OS_OSX
    #ifndef MAP_ANONYMOUS
      #ifndef MAP_ANON
        #define MAP_ANON 0x1000
      #endif // MAP_ANON
      #define MAP_ANONYMOUS MAP_ANON
    #endif // MAP_ANONYMOUS
  #endif // TARGET_OS_OSX
  mapped_addr= mmap(NULL, ARCUS_MAX_PROXY_FILE_LENGTH, PROT_WRITE | PROT_READ,
                    MAP_SHARED | MAP_ANONYMOUS, -1, 0);
#else
  mapped_addr= mmap(NULL, ARCUS_MAX_PROXY_FILE_LENGTH, PROT_WRITE | PROT_READ,
                    MAP_SHARED, -1, 0);
#endif
```

해당 방안 검토 부탁드립니다.

**Comment by uhm0311** [comment]
@jhpark816 

Windows 환경에서도 `MAP_ANONYMOUS` 혹은 `MAP_ANON` 플래그가 필요한지 여부 확인하고 처리 방안 검토 해보겠습니다.

**Comment by uhm0311** [comment]
@jhpark816 
- 조사 결과 MacOS 환경에서는 [`MAP_ANON`가 먼저 정의](https://github.com/apple/darwin-xnu/blob/3eaa6b2cf6d66cebc3974fffeb31fc70175aa59b/bsd/sys/mman.h) 되었고 그 이후 [버전이 올라가면서 `MAP_ANONYMOUS`가 추가](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/mman.h) 되었습니다.

> 어떻게 처리하면 좋은가요?

- `TARGET_OS_OSX`가 정의 되었을 때에도 `MAP_ANONYMOUS` 플래그를 사용해야 하니, MacOS 환경에서의 [`mman.h`](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/mman.h) 파일을 참고하여 아래와 같이 처리하는 방안을 검토해 보았습니다.

```cxx
#if defined(TARGET_OS_LINUX) || defined(TARGET_OS_OSX)
  #ifdef TARGET_OS_OSX
    #ifndef MAP_ANONYMOUS
      #ifndef MAP_ANON
        #define MAP_ANON 0x1000
      #endif // MAP_ANON
      #define MAP_ANONYMOUS MAP_ANON
    #endif // MAP_ANONYMOUS
  #endif // TARGET_OS_OSX
  mapped_addr= mmap(NULL, ARCUS_MAX_PROXY_FILE_LENGTH, PROT_WRITE | PROT_READ,
                    MAP_SHARED | MAP_ANONYMOUS, -1, 0);
#else
  mapped_addr= mmap(NULL, ARCUS_MAX_PROXY_FILE_LENGTH, PROT_WRITE | PROT_READ,
                    MAP_SHARED, -1, 0);
#endif
```

해당 방안 검토 부탁드립니다.

**Comment by jhpark816** [comment]
아래와 같이 코딩하는 것이 더 나을 것 같습니다.

```C
#if !defined(MAP_ANONYMOUS) // for TARGET_OS_OSX
  #if defined(MAP_ANON)
    #define MAP_ANONYMOUS MAP_ANON
  #else
    #define MAP_ANONYMOUS 0
  #endif
#endif

  mapped_addr= mmap(NULL, ARCUS_MAX_PROXY_FILE_LENGTH, PROT_WRITE | PROT_READ,
                    MAP_SHARED | MAP_ANONYMOUS, -1, 0);
  if (mapped_addr == MAP_FAILED) {
    ZOO_LOG_ERROR(("cannot map the proxy file"));
    return ARCUS_ERROR;
  }
```

**Comment by uhm0311** [comment]
@jhpark816 

제안해주신 방안으로 검토해보겠습니다. 감사합니다.

**Comment by uhm0311** [comment]
commit: https://github.com/naver/arcus-c-client/commit/173d374c592f2c9509c841f9b64520bb4a34bc83

https://github.com/naver/arcus-c-client/issues/206#issuecomment-1005387930
위 방안으로 수정하여 적용했습니다.
