### ISSUE TITLE
memcached_st 구조체에서 last_disconnected_server 필드의 필요성 검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#211]
memcached_st 구조체에 설정된 last_disconnected_server 값의 필요성을 재검토할 필요가 있다.

현재 last_disconnected_server 필드를 이용하는 부분을 살펴보면, 아래와 같다.
- memcached.cc 파일
  - `_memcached_init()` 함수(memcached_st 초기화)에서 last_disconnected_server를 NULL로 초기화한다.
  - `_free()` 함수(memcached_st 종료 or 리셋)에서 last_disconnected_server가 있으면 free한다. 
  - `memcached_servers_reset()` 함수에서 current server list를 free하면서 last_disconnected_server를 free한다.
  - `memcached_reset_last_disconnected_server()`에서  last_disconnected_server가 있으면 free한다.
- server.hpp 파일
  - `set_last_disconnected_host()` 함수에서 last_disconnected_server를 set한다.
    - 기존에 설정된 last_disconnected_server가 있으면 free 하며,
    - 주어진 server를 `memcached_server_clone()`하여 설정한다.

위와 같이 last_disconnected_server를 설정하거나 해제하는 작업만 있지만,
설정된 last_disconnected_server를 바탕으로 어떤 작업(재연결)을 수행하는 경우는 없다.
그러면,  last_disconnected_server 정보를 유지할 필요가 없다고 본다.

참고로, 어떤 memcached server를 사용할 때는 항상 정상 연결된 상태인지를 fd 값을 통해 확인하고,
invalid fd이면 다시 connect() 요청을 하기 때문에, last_disconnected_server 정보가 의미 없어 보인다.

**Comment by jhpark816** [comment]
@uhm0311 
최신 libmemcached 코드를 확인해 보시죠.

**Comment by uhm0311** [comment]
@jhpark816 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/server.h#L136-L137

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/server.cc#L315-L322

- 조사 결과 최신 libmemcached에서도 내부적으로 `last_disconnected_server`를 사용하는 곳은 없습니다. 
- [최신 버전에서도 위 코드와 같이 외부에서 `last_disconnected_server`를 사용할 수 있게 되어 있습니다.](https://bazaar.launchpad.net/~tangent-trunk/libmemcached/1.0/view/head:/libmemcached/instance.cc#L329)
- [libmemcached 문서에서는 `memcached_server_get_last_disconnect()` 함수에 대한 설명도 쓰여 있습니다.](http://docs.libmemcached.org/memcached_servers.html)
- `memcached_server_get_last_disconnect()` 함수를 사용하는 예제는 찾지 못했지만 내부적으로 사용하는 용도가 아닌, 외부에서 사용하는 용도로는 의미가 있는 것 같습니다.

**Comment by jhpark816** [comment]
@uhm0311 @SuhwanJang 
memcached_st 구조체에서 last_disconnected_server 용도는 
가장 최근에 disconnected 된 memcached server 정보를 제공하기 위한 것으로 봐야 할 것 같습니다.

반드시 필요한 기능은 아니지만,
최신 libmemcached에도 동일 코드가 있으니 기존 코드를 그대로 유지하겠습니다.
