### ISSUE TITLE
__do_arcus_update_cachelist() 함수의 수행 최적화

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#212]
__do_arcus_update_cachelist() 함수를 보면, 아래와 같이 새로 추가할 servers 목록을 구하여 추가하는 코드에서
2가지 최적화 부분이 있다.
- 추가할 server 목록의 준비에서 새로운 server가 있을 때마다 servers 배열을 realloc하여 추가하고 있다.
  - 추가할 server 개수를 미리 파악하여, 1회 malloc하고 server들을 추가할 수 있다.
  - 이 경우, 추가하는 각 memcached_server_st 구조체를 init 한다.
- memcached_server_push() 함수로 실제 servers 등록하는 경우에
  - servers array는 한번에 realloc으로 확장한다. 이 부분은 OK
  - 추가하는 memcached_server_st 구초체를 다시 init 한다. 결국 2회 init 수행하는 것이다.

```C
  for (x= 0; x< memcached_server_count(mc); x++)
  {
    for (y= 0; y< servercount; y++) {
      if (serverinfo[y].exist)
        continue;

      if (strcmp(mc->servers[x].hostname, serverinfo[y].hostname) == 0 and
          mc->servers[x].port == serverinfo[y].port) {
         serverinfo[y].exist= true; break;
      }
    }
    if (y == servercount) { /* NOT found */
      mc->servers[x].options.is_dead= true;
      prune_flag= true;
    }
  }
  for (x= 0; x< servercount; x++)
  {
    if (serverinfo[x].exist == false) {
      new_hosts= memcached_server_list_append(servers, serverinfo[x].hostname,
                                              serverinfo[x].port, &error);
      if (new_hosts == NULL)
        break;
      servers= new_hosts;
    }
  }
  . . .
  error= memcached_server_push(mc, servers);
```

어떻게 최적화하면 좋은 지를 설계하고, 수정한다.

**Comment by uhm0311** [comment]
@jhpark816 

memcached_server_list_append() 함수가 내부적으로 memcached_server_list_append_with_weight() 함수를 사용하는데, 두 함수 모두 하나의 hostname, port를 받고 있습니다. 이를 배열로 받을 수 있도록 수정하면 어떨까요?

**Comment by jhpark816** [comment]
@SuhwanJang 와 상의 바랍니다.

**Comment by jhpark816** [comment]
@uhm0311 @SuhwanJang
상의해 보았나요?

**Comment by SuhwanJang** [comment]
@jhpark816 
제가 아직 검토를 못해서 아직 상의 못 했습니다.

**Comment by SuhwanJang** [comment]
@uhm0311 @jhpark816
변경 방안 좋은 것 같습니다.
all_flag 인자는 사용될 횟수나 효과 모두 적어보여 없는 게 나을 것 같습니다.

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L1012-L1088

`bool push_flag = false`를 두고 다음과 같이 처리하는 방안은 어떨까요?

```cxx
if (push_flag) {
  if (prune_flag) {
    memcached_server_prune(mc, false); /* prune dead servers only */
  }
  error= memcached_server_push_with_serverinfo(mc, serverinfo, servercount);
} else {
  if (prune_flag) {
    memcached_server_prune(mc, false); /* prune dead servers only */
    error= run_distribution(mc);
  }
}
if (push_flag or prune_flag) {
  *serverlist_changed = true;
}
```

**Comment by uhm0311** [comment]
commit: https://github.com/naver/arcus-c-client/commit/8fb7abb7313d43537f3a89136e93f6c5ee066c5a
해당 커밋으로 수정했습니다.
