### ISSUE TITLE
memcached_st 정보의 ketama_version과 version 정보 관리의 개선 방안 검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#215]
memcached_st 정보의 버전으로 2가지 version 정보가 있습니다.
- ketama_version : servers와 hash ring 정보의 version
- version: ketama 정보를 제외한 나머지 속성 정보에 대한 version

위의 2 버전 정보의 관리 방식이 최적인 지 확인하고, 개선 방안이 있는 지를 검토한다.

**Comment by uhm0311** [comment]
@jhpark816 

- ketama_version을 ZK manager thread에서 write 하고 Worker thread에서 read 하여 생기는 동기화 문제 제외하고는 최적인 상태로 보입니다.

**Comment by uhm0311** [comment]
@jhpark816 

> ketama_version을 ZK manager thread에서 write 하고 Worker thread에서 read 하여 생기는 동기화 문제 제외하고는 최적인 상태로 보입니다.

https://github.com/naver/arcus-c-client/blob/b2f97f5f373ce3277a49776ca5e5ddf170470f89/libmemcached/util/pool.cc#L789-L812
797 라인의 `pool->increment_ketama_version();`

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/util/pool.cc#L566-L599
579 라인의 `pool->increment_ketama_version();`

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/util/pool.cc#L124-L127
memcached_pool_st::increment_ketama_version() 함수 내부입니다.

- ketama_version을 write 하는 위의 함수는 ZK manager thread에 의해 일어납니다.
- ketama_version을 read 하는 아래의 함수는 Worker thread에 의해 일어납니다.

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L702-L779
726 라인, 741 라인의 ketama_version read 하는 부분

**Comment by jhpark816** [comment]
@uhm0311 
ketama_version  따로 두는 이유가 충분해 보이나요?

**Comment by uhm0311** [comment]
@jhpark816 

- version을 통합하여 사용한다고 했을 때 behavior_set() 함수 호출로도 version이 바뀌고, 이를 read하는 쪽에서는 server list의 변경으로 인식할 수 있어서 따로 두는 게 맞아 보입니다.
