### ISSUE TITLE
master의 behavior 변경 후 pool의 멤버 mc에 적용하는 방법 개선

### ISSUE THREAD

**Issue by uhm0311** [naver/arcus-c-client#222]
https://github.com/naver/arcus-c-client/blob/7b5cf920f1efea242ca5e7ab684a6b739043bedd/libmemcached/util/pool.cc#L471-L516

https://github.com/naver/arcus-c-client/blob/7b5cf920f1efea242ca5e7ab684a6b739043bedd/libmemcached/arcus.cc#L331-L357

- 현재 코드는 master의 behavior 변경 후 pool의 멤버 mc에 적용하기 위해 repopulate 동작을 수행하고 있습니다.
- 일반적으로 arcus-c-client의 pool 사용법은 create -> behavior set -> get/set -> destroy이므로, behavior set 단계에서 repopulate 동작을 수행하는 것은 create 단계에서 이미 만들어져 할당된 pool의 멤버 mc 메모리를 해제하고 다시 할당하는 꼴이 됩니다.
- 이러한 repopulate 동작 수행은 리소스 낭비로 판단됩니다. 다만 behavior set 단계만 본다면 전체적인 동작 시간에는 큰 영향을 미치지 않습니다.
- 아래와 같은 함수를 이용해 repopulate 동작 대신, 변경된 behavior를 반영할 수 있도록 하면 좋을 것 같습니다.

```cxx
memcached_return_t memcached_copy_fields(memcached_st *ptr, const memcached_st *master)
{
  if (not ptr or not master) {
    return MEMCACHED_INVALID_ARGUMENTS;
  }

  if (ptr->hashkit.options.is_allocated) {
    hashkit_free(&ptr->hashkit);
  }
  
  if (not hashkit_clone(&ptr->hashkit, &master->hashkit)) {
    return MEMCACHED_MEMORY_ALLOCATION_FAILURE;
  }

  memcached_return_t rc;

  if ((memcached_server_count(ptr) == 0) and (memcached_server_count(master) > 0))
  {
    if (memcached_failed(rc= memcached_push(ptr, master))) {
      return rc;
    }
  }

  if (LIBMEMCACHED_WITH_SASL_SUPPORT and master->sasl.callbacks)
  {
    if (ptr->sasl.callbacks)
    {
      if (memcached_failed(rc= memcached_destroy_sasl_auth_data(ptr))) {
        return rc;
      }
    }

    if (memcached_failed(rc = memcached_clone_sasl(ptr, master))) {
      return rc;
    }
  }

  ptr->flags= master->flags;
  ptr->send_size= master->send_size;
  ptr->recv_size= master->recv_size;
  ptr->poll_timeout= master->poll_timeout;
  ptr->connect_timeout= master->connect_timeout;
  ptr->retry_timeout= master->retry_timeout;
  ptr->distribution= master->distribution;
  ptr->ketama.weighted= master->ketama.weighted;
#ifdef LIBMEMCACHED_WITH_ZK_INTEGRATION
  if (ptr->server_manager and ptr->server_manager != master->server_manager) {
    libmemcached_free(ptr, ptr->server_manager);
  }

  ptr->server_manager= master->server_manager;
  ((arcus_st *)ptr)->proxy= ((arcus_st *)master)->proxy;
#endif
  if (ptr->user_data && ptr->user_data != master->user_data) {
    libmemcached_free(ptr, ptr->user_data);
  }

  ptr->user_data= master->user_data;

  ptr->snd_timeout= master->snd_timeout;
  ptr->rcv_timeout= master->rcv_timeout;

  ptr->on_clone= master->on_clone;
  ptr->on_cleanup= master->on_cleanup;

  ptr->allocators= master->allocators;

  ptr->get_key_failure= master->get_key_failure;
  ptr->delete_trigger= master->delete_trigger;
  ptr->server_failure_limit= master->server_failure_limit;
  ptr->io_msg_watermark= master->io_msg_watermark;
  ptr->io_bytes_watermark= master->io_bytes_watermark;
  ptr->io_key_prefetch= master->io_key_prefetch;
  ptr->number_of_replicas= master->number_of_replicas;
  ptr->tcp_keepidle= master->tcp_keepidle;

  if (ptr->_namespace and ptr->_namespace != master->_namespace) {
    memcached_array_free(ptr->_namespace);
  }
  
  ptr->_namespace= memcached_array_clone(ptr, master->_namespace);

  if (ptr->configure.filename and ptr->configure.filename != master->configure.filename) {
    memcached_array_free(ptr->configure.filename);
  }

  ptr->configure.filename= memcached_array_clone(ptr, master->_namespace);
#ifdef UPDATE_HASH_RING_OF_FETCHED_MC
  ptr->configure.ketama_version= master->configure.ketama_version;
#endif
  ptr->configure.version= master->configure.version;

  if (master->on_clone) {
    master->on_clone(ptr, master);
  }

  return MEMCACHED_SUCCESS;
}
```

**Comment by jhpark816** [comment]
@uhm0311 
- version 변경되는 모든 경우를 먼저 확인해 보시죠.
   - behavior 설정 외에 다른 경우가 있는 지를 먼저 확인하고, 처리 방식을 논의하시죠.
- behavior 설정만 있다면,
   - 이 연산 자체는 실패할 이유가 없다고 보입니다.
   - 무엇 때문에 실패하는 지를 먼저 확인하는 것이 좋겠습니다.

**Comment by uhm0311** [comment]
@jhpark816 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L408-L476

- do_arcus_init() 함수 수행 후 master mc와 pool의 member mc의 차이점은 다음과 같습니다.
  1. memcached_behavior_set()으로 바뀐 behavior  
  2. server manager 소유 여부  
- 처음에는 copy_fields() 함수를 고안했으나 memcached_pool_behavior_set() 함수가 있고, server manager를 set 해주기만 하면 master mc와 pool member mc 간 차이는 없습니다. 따라서
  1. 420 ~ 423라인의 memcached_behavior_set() 함수 호출을  memcached_pool_behavior_set() 함수 호출로 변경하고
  2. 463 라인의 memcached_set_server_manager() 함수 호출을 memcached_pool_set_server_manager() 함수 호출로 변경하면 됩니다.
  3. memcached_pool_set_server_manager() 함수는 새로 만들어야 할 함수이며, memcached_pool_behavior_set() 함수는 다음과 같습니다.

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/util/pool.cc#L471-L521

**Comment by uhm0311** [comment]
@jhpark816 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L408-L476

- do_arcus_init() 함수 내에서 중복 behavior set이 있습니다. 419 라인의 `mc->flags.use_sort_hosts= false;`는 기본값이 이미 false 입니다. 다음의 코드 94 라인에서 false로 초기화 합니다.

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/memcached.cc#L78-L188

  - do_arcus_init() 함수의 422 라인의 `memcached_behavior_set(mc, MEMCACHED_BEHAVIOR_KETAMA_WEIGHTED, 1);`와 425 라인의 `memcached_behavior_set_key_hash(mc, MEMCACHED_HASH_MD5);`는 중복입니다. 다음의 코드 172 라인에서 동일한 호출을 합니다.

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/behavior.cc#L170-L179

**Comment by jhpark816** [comment]
@uhm0311 
본 이슈를 어떻게 처리하면 되는 지 개념적으로 요약해 보시죠.

**Comment by uhm0311** [comment]
@jhpark816

commit: https://github.com/naver/arcus-c-client/commit/b6722167f9bcb9a951f05a42a1aaacc8b86d5f42
위 commit 기준으로, clone 동작 시 발생하는 문제점은 다음과 같습니다.

1. 최초로 pool_update_cachelist() 함수 호출할 때 이미 할당된 메모리를 해제하고 다시 할당하는 점
2. pool_push() 함수 호출 시 version이 안 맞을 때 clone 동작으로 인해 released_mc의 연결이 모두 끊어지는 점

1번은 init size 만큼의 grow pool을 pool_create() 함수에서 하지 않고, 최초로 pool_update_cachelist() 함수 호출하는 시점에 수행하면 됩니다.
위 commit 기준의 이 이슈에서 개선하고자 하는 문제점은 2번입니다. version이 다를 때 연결을 유지하면서 master의 properties를 가져오려면 첫 코멘트에 제안한 바와 같은 함수를 사용하면 됩니다.

> 이 연산 자체는 실패할 이유가 없어 보입니다.
무엇 때문에 실패하는 지를 먼저 확인하는 것이 좋겠습니다.

함수가 실패하는 경우를 모두 살펴봤는데, 메모리가 부족한 경우에 실패합니다.

**Comment by jhpark816** [comment]
@uhm0311 @SuhwanJang 
상의해 보기 바랍니다.

**Comment by SuhwanJang** [comment]
@jhpark816 @uhm0311 
상의한 결과 아래와 같이 정리하였습니다.
- behavior 변경으로 인해 member mc 반영은 clone 수행 (기존 방식 유지)
  - behavior 변경 시 reconnect 가 필요한 behavior 가 있음. ex. tcp_nodelay, tcp_keepalive ..
          - 기존에 해당 behavior 변경 시 memcached_behavior_set() 내부에서 servers connection 을 모두 끊어주고 있긴 하나
          - 위에 해당하지 않은 behavior 는 clone 하지 않고 behavior 값만 복사하여 최적화가 필요한 지는 의문임.   
  - behavior 변경이 드물기도 하고 변경이 실패하는 경우는 거의 없음. (deprecate behavior 를 변경하거나 값을 잘못 준 경우 실패)
    - 위의 이유 포함하여 최적화 필요한지 의문이고 memcached_pool_behavior_set() 에서 변경 실패 시 clone() 하는 로직은 제거해도 무방할 것 같으나 원작자 의도를 모르니 일단 기존 libmemcached 코드 유지하는 게 나을 것 같음.

**Comment by jhpark816** [comment]
@SuhwanJang @uhm0311 
그럼, 본 이슈는 close 합니다.
