### ISSUE TITLE
proxy 통한 cache list 변경 방식의 오류 

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#229]
cache_list zk 이벤트 시에 proxy mc가 변경되고 나면,
proxy 이용하는 standalone mc or mc pool은 arcus_server_check_for_update() 함수에서
proxy 통해 cache_list 변경 내역을 전달받아 mc or mc pool에 반영한다.

이 경우, 기존 코드의 문제점은
- member mc인 경우에도 do_arcus_zk_update_cachelist_by_string() 호출한다는 것이다.
  - 결국, do_arcus_update_cachelist() 호출하여
  - pool과 독립적으로 cachelist 변경하고 ketama_version은 변경하지 않는 문제가 있다.
- 예전 버전에서
  - 서로 독립적인 ketama hashring 가질 경우에는 큰 문제가 없었지만,
  - release 시에 ketama_version 달라서 다시 clone하는 비효율성은 있었다.

따라서, member mc인 경우는
memcached_pool_update_member() 호출하도록 수정하여야 한다.

**Comment by jhpark816** [comment]
arcus_server_check_for_update() 함수의 로직을 아래와 같이 수정합니다.
아래 코드에서
- master mc 변경하는 경우 ketama_version 비교는 없어도 된다고 봅니다.
   - 이미 proxy data version 비교하여 수행하므로, master mc 변경은 1회만 발생합니다.
   - ketama_version 비교가 있어도 문제는 없으므로, 일단 기존 형태를 그대로 유지해 두었습니다.
   - @uhm0311 이 부분 살펴봐 주기 바랍니다.
- member mc는 하단의 `if (arcus->pool)` 문장에서 변경하도록 수정하였습니다.

```C
  if (arcus->proxy.data && arcus->proxy.data->version != arcus->proxy.current_version)
  {
    proc_mutex_lock(&arcus->proxy.data->mutex);
    {
      version= arcus->proxy.data->version;
      size= arcus->proxy.data->size;
      if (arcus->pool) {
        /* As the proxy data version is compared, the master is updated just once */
        memcached_st *master = memcached_pool_get_master(arcus->pool);
#ifdef UPDATE_HASH_RING_OF_FETCHED_MC
        if (master && master->configure.ketama_version == ptr->configure.ketama_version)
#else
        if (master && master->configure.version == ptr->configure.version)
#endif
        {
          do_arcus_zk_update_cachelist_by_string(master, arcus->proxy.data->serverlist, size);
        }
      } else {
        do_arcus_zk_update_cachelist_by_string(ptr, arcus->proxy.data->serverlist, size);
      }
      arcus->proxy.current_version= version;
    }
    proc_mutex_unlock(&arcus->proxy.data->mutex);
  }

  if (arcus->pool)
  {
    memcached_st *master = memcached_pool_get_master(arcus->pool);
#ifdef UPDATE_HASH_RING_OF_FETCHED_MC
    if (master && master->configure.ketama_version != ptr->configure.ketama_version)
#else
    if (master && master->configure.version == ptr->configure.version)
#endif
    {
      /* master's cache list was changed, update member's cache list */
      pthread_mutex_lock(&lock_arcus);
      (void)memcached_pool_update_member(arcus->pool, ptr);
      pthread_mutex_unlock(&lock_arcus);
    }
  }
```

@SuhwanJang @uhm0311 
아래 수정 코드를 확인하기 바랍니다.
- commit) https://github.com/naver/arcus-c-client/commit/e1e1957fd49645264730cf7cf0ad892c1494ed87

**Comment by uhm0311** [comment]
@jhpark816 

> master mc 변경하는 경우 ketama_version 비교는 없어도 된다고 봅니다.

- proxy server list 업데이트 방식을 보니 불필요한 부분으로 보입니다.

> 아래 수정 코드를 확인하기 바랍니다.

- 아래 코드에서 질문이 있습니다.

```cxx
  if (arcus->pool)
  {
    memcached_st *master = memcached_pool_get_master(arcus->pool);
#ifdef UPDATE_HASH_RING_OF_FETCHED_MC
    if (master && master->configure.ketama_version != ptr->configure.ketama_version)
#else
    if (master && master->configure.version == ptr->configure.version)
#endif
    {
      /* master's cache list was changed, update member's cache list */
      pthread_mutex_lock(&lock_arcus);
      (void)memcached_pool_update_member(arcus->pool, ptr);
      pthread_mutex_unlock(&lock_arcus);
    }
  }
```

- `if (master && master->configure.version == ptr->configure.version)` 부분에서 == 연산자가 아니고 != 연산자를 사용해야 하지 않나요?

**Comment by jhpark816** [comment]
@uhm0311
`(master && master->configure.version == ptr->configure.version)` 부분은 실수로 `!=`로 변경되어야 합니다.  Thanks.
