### ISSUE TITLE
#pragma once 제거

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#233]
비표준인 pragma 사용을 아래 형태로 변경합시다.

```C
#ifndef XXXX_H
#define XXXX_H

...

#endif
```

참고 링크) https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=knix008&logNo=220677718417

**Comment by jhpark816** [comment]
@SuhwanJang 
본 이슈를 처리하는 것이 나은가요?

**Comment by SuhwanJang** [comment]
@jhpark816 
변경이 어렵지 않으므로 표준 사용이 나은 것 같습니다.

**Comment by jhpark816** [comment]
PR merge 상태이므로, close 합니다.
