### ISSUE TITLE
memcached_exist_by_key() 함수에서 arcus_server_check_for_update() 함수 호출 필요성 검토

### ISSUE THREAD

**Issue by uhm0311** [naver/arcus-c-client#240]
https://github.com/naver/arcus-c-client/blob/83073f1c152fdf745f3b906c45682c165213f9ec/libmemcached/exist.cc#L151-L186

memcached_exist_by_key() 함수입니다. 이 함수는 memcached 노드에게 add 요청을 보내 key가 저장되어 있는지 없는지 여부를 확인하는 함수인데, memcached 노드와의 통신 전 arcus_server_check_for_update() 함수를 호출하지 않습니다.
binary_exist() 함수와 ascii_exist() 함수 내에서도 arcus_server_check_for_update() 함수를 호출하지 않습니다.
@SuhwanJang 님과 상의한 결과 arcus_server_check_for_update() 함수를 호출해야 하는 것으로 보입니다.
@jhpark816 이 함수에만 arcus_server_check_for_update() 함수 호출이 없는 이유가 따로 있다면 공유 부탁드립니다.

**Comment by jhpark816** [comment]
exist 검사는 어떤 ascii 명령을 사용하고 있나요 ?

**Comment by uhm0311** [comment]
@jhpark816 

add 명령어를 사용해 STORED이면 이전에 key가 서버에 없었다는 의미이므로 MEMCACHED_NOT_FOUND를 반환합니다.
반대로 NOT_STORED이면 이전에 key가 서버에 있었다는 의미이므로 MEMCACHED_SUCCESS를 반환합니다.

**Comment by jhpark816** [comment]
@uhm0311 @SuhwanJang 
짐작으론, arcus에서 정식으로 제공하지 않는 API라서 제외했던 것이라 생각되네요.
예를 들어, 테스트나 기타 용도로 한정되지 않았나 생각됩니다.
- arcus에서 정식으로 제공하지 않는다면,
   - arcus 사용하여 호출된다면 not supported 오류를 리턴해야 할 것 같고,
- arcus에서 정식으로 제공한다면,
   - add 연산이 아닌 getattr 연산을 사용하여 exist 검사해야 할 것 같고,
   - arcus_server_check_for_update() 함수도 호출해야 할 것 같습니다.

어떻게 처리하는 것이 맞을까요?

**Comment by SuhwanJang** [comment]
@jhpark816 @uhm0311 
사용할 여지가 있을 것 같은 API 여서 저는 정식 제공 방향으로 수정이 좋을 것 같습니다.

**Comment by jhpark816** [comment]
OK. 그렇게 진행하시죠.

**Comment by uhm0311** [comment]
PR merge 되어 close 합니다.
