### ISSUE TITLE
github action을 통한 CI 도입

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#251]
아래는 github action에서 travis ci를 migration 할 수 있는 방법을 설명하고 있다.

https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

현재 travis ci는 yml 형태로 되어 있어 문서 내용을 참고하여 비슷하게 github action도 적용할 수 있다고 한다.
해당 링크를 참고하여 github action을 도입할 수 있는 방안을 검토한다.

그리고, java client에 CI 도입한 commit은 참고하고, 필요하면 @hjyun328 님과 상의하세요.
https://github.com/naver/arcus-java-client/pull/456

**Comment by ing-eoking** [comment]
Java Client, C Client 모두 CI 테스트가 추가되었으므로 해당 이슈 닫겠습니다.
