### ISSUE TITLE
내부에서 사용되는 API의 type 변경

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-c-client#29]
현재 collection 구조에서 사용하는
xxx_query_init() 함수의 API type은 LIBMEMCACHED_API 이다.
LIBMEMCACHED_API type은 application에서 호출 하는 type 이다.
application에서 호출하지 않는 type은 LIBMEMCACHED_LOCAL 이다.

xxx_query_init()을 application에서 호출하는 collection은 b+tree가 유일하다.
API type을 점검하고, 내부에서만 사용하는 API 는 LOCAL type으로 변경 한다.

**Comment by jhpark816** [comment]
xxxx_query_init()은 아래와 같이 외부 API로 정리합니다.
- b+tree docs에 설명된 외부 API이며,
- 다른 collection 경우는 docs에 설명되지 않았지만, 일관되게 외부 API로 정의합니다.
