### ISSUE TITLE
response return에 따른 에러 처리 검토.

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-c-client#31]
현재 response를 read하는 함수의 return으로,
```
MEMCACHED_UNKNOWN_READ_FAILURE or
MEMCACHED_PROTOCOL_ERROR or
MEMCACHED_CLIENT_ERROR or
MEMCACHED_MEMORY_ALLOCATION_FAILURE
```
에 대해 io reset을 진행 한다.
io reset은 현재 connection을 끊고, 2초 wait 뒤 reconnect 하는 과정을 거친다.

아래의 return에 대해서는 wait할 필요가 없지만 현재는 wait 하도록 되어 있다.
```
UNKNOWN_READ_FAILURE or
PROTOCOL_ERROR or
CLIENT_ERROR
```
에 대해서 즉시 reconnect 하도록 변경이 필요하다.
quit_server() 동작에서 몇가지 검토가 필요하다.
- 즉시 reconnect 하도록 변경할 때 정상 동작 여부
- ascii protocol 일 때 ```quit```명령으로 telnet을 종료 하는데, 위 동작의 필요성.

검토 후 문제없이 동작 가능 하다면 즉시 reconnect 하도록 변경 한다.

**Comment by jhpark816** [comment]
@SuhwanJang 

본 이슈가 아래 commit에서 모두 해결된 것인 지 살펴봐 주세요.
commit - https://github.com/naver/arcus-c-client/commit/1d955cad5a769d9e822673aa247a76d74f64f7ba

**Comment by SuhwanJang** [comment]
ascii protocol 일 때 quit명령으로 telnet을 종료 동작의 필요성은 이슈를 따로 생성하겠습니다.
response return에 따른 reconnect는 1d955ca 에 반영되었습니다.
- CLIENT_ERROR, PROTOCOL_ERROR, SERVER_ERROR, PARTIAL_READ에 대해 즉시 reconnect 합니다.

**Comment by jhpark816** [comment]
- MEMCACHED_UNKNOWN_READ_FAILURE는 delayed reconnect가 맞나요 ?

**Comment by SuhwanJang** [comment]
@jhpark816 
검토해보니 MEMCACHED_UNKNOWN_READ_FAILURE는 immediate reconnect가 맞다고 봅니다.
위 에러가 발생하는 경우는 
 - client 가 기대하는 server response가 오지 않은 경우 : protocol 차이일 뿐이므로 immediate reconnect 
 - socket error(recv < 0)의 응용 오류 코드. 에를 들어 recv() 에서 EXXX 에러 발생한 경우 이를 그대로 응용에게 전달하지 않고, MEMCACHED_UNKNOWN_READ_FAILURE로 전달. 이 경우에 io 모듈단에서 delayed reconnect 하도록 되어 있음.
참고 코드:
```
 static memcached_return_t binary_read_one_response(memcached_server_write_instance_st ptr,
                                                    char *buffer, size_t buffer_length,
                                                    memcached_result_st *result)
 {
...
     case PROTOCOL_BINARY_CMD_GETK:
       {
..
         if ((rc= memcached_safe_read(ptr, &result->item_flags, sizeof (result->item_flags))) != MEMCACHED_SUCCESS)
         {
           WATCHPOINT_ERROR(rc);
           return MEMCACHED_UNKNOWN_READ_FAILURE;
         }
```
```
 memcached_return_t memcached_safe_read(memcached_server_write_instance_st ptr,
                                        void *dta,
                                        size_t size)
 {
   size_t offset= 0;
   char *data= static_cast<char *>(dta);

   while (offset < size)
   {
     ssize_t nread;
     memcached_return_t rc;
    // #define memcached_continue(__memcached_return_t) ((__memcached_return_t) == MEMCACHED_IN_PROGRESS)
     while (memcached_continue(rc= memcached_io_read(ptr, data + offset, size - offset, &nread))) { };

     if (memcached_failed(rc))
     {
       return rc;
     }

     offset+= (size_t) nread;
   }

   return MEMCACHED_SUCCESS;
 }
```
 memcached_return_t memcached_io_read(memcached_server_write_instance_st ptr,
                                      void *buffer, size_t length, ssize_t *nread)
 {
   assert_msg(ptr, "Programmer error, memcached_io_read() recieved an invalid memcached_server_write_instance_st"); // Programmer      error
   char *buffer_ptr= static_cast<char *>(buffer);

   if (ptr->fd == INVALID_SOCKET)
   {
     //assert_msg(int(ptr->state) <= int(MEMCACHED_SERVER_STATE_ADDRINFO), "Programmer error, invalid socket state");
     fprintf(stderr, "[DEBUG] invalid server state : %d, hostname : %s\n", ptr->state, ptr->hostname);
     return MEMCACHED_CONNECTION_FAILURE;
   }

   while (length)
   {
     if (not ptr->read_buffer_length)
     {
       ssize_t data_read;
       do
       {
         data_read= recv(ptr->fd, ptr->read_buffer, MEMCACHED_MAX_BUFFER, MSG_DONTWAIT);
         if (data_read == SOCKET_ERROR)
         {
           switch (get_socket_errno())
           {
           case EINTR: // We just retry
             continue;

           case ETIMEDOUT: // OSX
           case EWOULDBLOCK:
 #ifdef USE_EAGAIN
           case EAGAIN:
 #endif
 #ifdef TARGET_OS_LINUX
           case ERESTART:
 #endif
             if (memcached_success(io_wait(ptr, MEM_READ)))
             {
               continue;
             }
             return MEMCACHED_IN_PROGRESS;

             /* fall through */

           case ENOTCONN: // Programmer Error
             WATCHPOINT_ASSERT(0);
           case ENOTSOCK:
             WATCHPOINT_ASSERT(0);
           case EBADF:
             assert_msg(ptr->fd != INVALID_SOCKET, "Programmer error, invalid socket");
           case EINVAL:
           case EFAULT:
           case ECONNREFUSED:
           default:
             {
//socket error : delayed reconnect
               memcached_quit_server(ptr, true);
               *nread= -1;
               return memcached_set_errno(*ptr, get_socket_errno(), MEMCACHED_AT);
             }
           }
         }
         else if (data_read == 0)
         {
           /*
             EOF. Any data received so far is incomplete
             so discard it. This always reads by byte in case of TCP
             and protocol enforcement happens at memcached_response()
             looking for '\n'. We do not care for UDB which requests 8 bytes
             at once. Generally, this means that connection went away. Since
             for blocking I/O we do not return 0 and for non-blocking case
             it will return EGAIN if data is not immediatly available.
           */
           WATCHPOINT_STRING("We had a zero length recv()");
           memcached_quit_server(ptr, true);
           *nread= -1;
           return memcached_set_error(*instance, MEMCACHED_CONNECTION_FAILURE, MEMCACHED_AT,
                                      memcached_literal_param("recv() returned zero, server has disconnected"));
         }
       } while (data_read <= 0);
...
```
MEMCACHED_UNKNOWN_READ_FAILURE를 immediate reconnect 하도록 변경 후 close하겠습니다.

**Comment by SuhwanJang** [comment]
아래 에러에 대해 immediate reconnect 합니다.
1d955ca
- CLIENT_ERROR, PROTOCOL_ERROR, SERVER_ERROR, PARTIAL_READ

https://github.com/naver/arcus-c-client/commit/ed888db0e792d5ec9870136f977ff9141614c3f9
- UNKNOWN_READ_FAILURE
