### ISSUE TITLE
cache list 변경 없다면, memcached_pool_repolulate 수행을 생략.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#53]
아래 2가지를 확인하고, 문제가 있으면 처리한다.
- cache list 변경이 없는 시에도 do_arcus_update_cachelist() 함수가 호출되는가 ?
   - 호출된다면, 그 이유를 확인할 필요 있음.
- cache list 변경이 없을 시에 do_arcus_update_cachelist() 함수가 호출되더라도
   - memcached_pool_repolulate()는 수행되지 않아야 함.
   - large pool에 대해 큰 부담을 발생시키고 있음.

**Comment by jhpark816** [comment]
Cache list 변경이 없어도 do_arcus_update_cachelist() 함수가 호출될 수 있음.

아래 답변 참고

---------

session event state
- 해당 c client 가 연결된 ZK 재구동 시
   - leader 재구동 시
      - Host Down error 발생
      - CONNECTING state
      - CONNECTED state
      - cache list update
   - follower 재구동 시
      - 없음
- 해당 c client가 연결되지 않은 ZK 재구동 시
   - 없음​

arcus c client 에서 CONNECTED state 일 때 cache list update 하는 로직은 정상적인 로직 입니다.
connection이 끊기고 reconnect 가 완료될 때 가지 watcher event가 발생하면 noti를 받지 못하게 되고, watcher를 잃어버리게 될 수 있습니다.  따라서, CONNECTED state가 되면 항상 cache list update를 수행 하면서 watcher를 다시 거는 게 안전합니다.
​
> [ZooKeeper Programmer's Guid]
> 1. If you are using watches, you must look for the connected watch event. When a ZooKeeper client disconnects from a server, you will not receive notification of changes until reconnected. If you are watching for a znode to come into existence, you will miss the event if the znode is created and deleted while you are disconnected.​

master_mc server list를 확인해서 변경이 있을 때만 repopulate 하도록 하는 정도의 수정이면 될 것 같습니다.

**Comment by jhpark816** [comment]
Master_mc의 server list 변경이 있을 경우만, repopulate 하도록 수정하였습니다.
- commit : https://github.com/naver/arcus-c-client/commit/c70c6b59ed327e91830c10cff3573557a9eccf26

**Comment by MinWooJin** [comment]
추가로, ZooKeeper Programmer's Guild를 보면 [link](https://zookeeper.apache.org/doc/r3.3.6/zookeeperProgrammers.html)
watcher 설명에 아래와 같은 내용이 언급되어 있습니다.
```
There is one case where a watch may be missed:
  a watch for the existance of a znode not yet created will be missed
  if the znode is created and deleted while disconnected.
```
