### ISSUE TITLE
memcached pool scalability 이슈 해결.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-c-client#59]
memcached pool size가 큰 경우, 아래 작업은 pool의 모든 memcached에 대해 clone 작업으로 반영하며 pool size에 비례하여 긴 시간이 소요되며, 그 동안에 서비스가 불가한 상태가 된다.

- behavior 변경
- cahce list 변경 (by ZK notification)

Cache list 변경은 자주 발생할 수 있어서, memcached pool scalability 이슈가  실 사용에 문제 된다.
Cache list 변경에서 pool의 모든 memcached에 반영할 사항은 2가지가 있다.
- server list (모든 cache node와의 연결 정보 유지)
- hash ring (각 요청을 어떤 cache node로 보내야 할 지를 결정하는 매커니즘에서 필요한 정보)

위의 2가지 중에 hashring 문제는
pool에 하나의 shared hashring을 두고, 모든 memcached가 공유하여 사용하도록 수정하여
해결한 상태이다.
- commit link: https://github.com/naver/arcus-c-client/commit/22921ed9fd17c409bc76d0c9def951d375ef8ac3

server list 문제는 남아 있는 상태이며,
현재 모든 server들을 close한 후에 새로운 server들을 생성하여 추가하는 방식으로 처리하고 있다.
이에 대해 아래 방식으로 개선이 필요하다.

- 전체 server 목록 중, 변경된 server들만 빠르게 찾고,
- 변경만 server들만 교체

**Comment by jhpark816** [comment]
@uhm0311 
본 이슈에서 server list 변경 시에 변경된 server들만 교체하는 작업을 진행 바랍니다.

**Comment by uhm0311** [comment]
@jhpark816 
혹시 아래의 함수가 cache list에서 server list가 변경될 때 사용하는 함수인가요?

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L1012-L1088

**Comment by jhpark816** [comment]
@uhm0311 
코드 분석하면서 궁금한 사항은 @SuhwanJang 에게 문의하시죠.

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

> server list 변경 시에 변경된 server들만 교체

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L933-L1138

위 코드를 참고하여 다음과 같은 형태로 변경된 server만을 교체하는 코드를 작성하려 합니다.

```cpp
memcached_return_t memcached_pool_update_cachelist(memcached_pool_st *pool,
                                                   struct memcached_server_info *serverinfo,
                                                   uint32_t servercount)
{
  if (pool == NULL)
  {
    return MEMCACHED_INVALID_ARGUMENTS;
  }

  if (pthread_mutex_lock(&pool->mutex))
  {
    return MEMCACHED_IN_PROGRESS;
  }

#ifdef UPDATE_HASH_RING_OF_FETCHED_MC
  pool->increment_ketama_version();
#else
  pool->increment_version();
#endif
  memcached_return_t rc= MEMCACHED_SUCCESS;

  for (int xx= 0; xx <= pool->top; ++xx)
  {
#ifdef ENABLE_REPLICATION
  if (pool->master->flags.repl_enabled)
    rc= __do_memcached_pool_update_grouplist(pool->mc_pool[xx], serverinfo, servercount);
  else
#endif
    rc= __do_memcached_pool_update_cachelist(pool->mc_pool[xx], serverinfo, servercount);
    
    if (rc != MEMCACHED_SUCCESS)
      break;
  }

  (void)pthread_mutex_unlock(&pool->mutex);
  return rc;
}
```

`__do_arcus_update_grouplist()` 함수와 `__do_arcus_update_cachelist()` 함수의 내부 구현을 참고하여 `__do_memcached_pool_update_grouplist()` 함수와 `__do_memcached_pool_update_cachelist()` 함수도 추가하려고 합니다. 함수 내용이 중복될 텐데, `__do_arcus_update_grouplist()` 함수와 `__do_arcus_update_cachelist()` 함수를 가져다 쓰는 방향으로 수정하는 것은 코드 구조가 변경되는 일이며 불필요한 `zookeeper` 로그가 추가된다고 판단되어 위의 코드 디자인만 검토해 보았습니다. 올바른 방향인지 검토 부탁드립니다.

**Comment by jhpark816** [comment]
@SuhwanJang 먼저 검토해 주세요.

**Comment by SuhwanJang** [comment]
@uhm0311 
수정 방향은 맞는 것 같습니다.
별도 함수 추가하지 않고 `__do_arcus_update_grouplist()` `__do_arcus_update_cachelist()` 를 사용하면 될 것 같고,
기존에  `memcached_pool_repopulate()` 를 호출하는 곳이 여러 군데 있는데 다 맞아 들어가는지 검토해봐야 할 것 같습니다.

**Comment by jhpark816** [comment]
@SuhwanJang @uhm0311 
내용 확인하였고, 아래 부분만 신경 써 주시면 될 것 같습니다.
- 모듈 간의 interface 정리
- multi-threaded 환경 뿐만 아니라 multi-process 환경 고려

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

> 모듈 간의 interface 정리

- `memcached_pool_update_cachelist()` 함수는 `memcached_pool_st` 구조체의 멤버 변수와 멤버 함수를 사용하고 있습니다. `pool` 모듈 외에서는 `memcached_pool_st` 구조체의 멤버 변수와 멤버 함수에 직접 접근이 불가능하니 `memcached_pool_update_cachelist()` 함수를 다른 모듈에 두려면 멤버 변수와 멤버 함수를 제공하는 함수를 추가로 작성해야 합니다. 그렇게 하는 것 보단 `pool` 모듈 안에 `memcached_pool_update_cachelist()` 함수를 넣는 방안이 좋아 보입니다.
- `__do_arcus_update_grouplist()` 함수와 `__do_arcus_update_cachelist()` 함수를 `pool` 모듈과 `arcus` 모듈에서 공통으로 사용하려면 함수의 이름을 `memcached_update_...()`으로 변경하고, 두 함수 모두 `memcached_st` 구조체의 내부 정보를 바꾸는 함수이니 `memcached` 모듈에 넣는 방안이 좋아 보입니다.

두 방안 검토 부탁드립니다.

**Comment by jhpark816** [comment]
@uhm0311 @SuhwanJang 
아래와 같이 이해됩니다. 맞다면 적절해 보이므로 그렇게 진행하시죠.
- `memcached_update_cachelist()` 함수를 memcached 모듈에서 제공
   - `__do_memcached_update_grouplist()` 함수와 `__do_memcached_update_cachelist()` 함수를 내부 함수(static functions)로 두고 이를 호출하여 구현
- arcus 모듈에서 pool의 master_mc의 cachelist 변경 시에 `memcached_update_cachelist()` 함수를 호출
- pool 모듈에서 내부 mc들의 cachelist 변경 시에  `memcached_update_cachelist()` 함수를 호출

하나 언급할 사항은 아래 2 경우의 interface가 다른데, 다른 interface를 제공할 것인지 아니면 하나의 interface로 통일할 것인지가 궁금합니다.
- server list 입력으로 master_mc 변경하는 경우
- master_mc 입력으로 다른 mc 변경하는 경우

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

> 하나 언급할 사항은 아래 2 경우의 interface가 다른데, 서로 다른 interface를 제공할 것인지 아니면 하나의 interface로 통일할 것인지가 궁금합니다.

- 두 경우 모두 `memcached_st *mc, struct memcached_server_info *serverinfo, uint32_t servercount` 매개변수가 필요하다고 판단됩니다. 따라서 통일된 interface로 제공하면 될 것 같습니다.

**Comment by jhpark816** [comment]
@uhm0311 
- server list 인자를 가지는 함수를 사용하겠다는 말이군요. 일단 이렇게 진행하시죠.
- master_mc 인자를 가지는 함수가 필요 없는 이유는 궁금합니다. 아래 2가지 이유인가요?
  - 호출하는 쪽에서 server list 가지고 호출이 가능하기 때문
  - server list 인자이든 master_mc 인자이든 내부 구현 로직과 효율성은 동일

**Comment by uhm0311** [comment]
@jhpark816 

> master_mc 인자를 가지는 함수가 필요 없는 이유는 궁금합니다.

- `pool` 모듈에서는 `pool->mc_pool[i]`로 `memcached_update_cachelist()` 함수의 `mc` 매개변수를 줄 수 있는데, 이것이 `master_mc`인지 아닌지는 `memcached_update_cachelist()` 함수 내에서 판별하여 분기할 로직이 없어서 필요하지 않다고 판단했습니다.

> 호출하는 쪽에서 server list 가지고 호출이 가능하기 때문

- 네 맞습니다.

> server list 인자이든 master_mc 인자이든 내부 구현 로직과 효율성은 동일

- `server list` 정보를 초기화 하는 곳이 `arcus` 모듈의 `do_arcus_zk_update_cachelist()` 함수입니다. zookeeper 통신으로 데이터를 가져와야 하며 `master_mc`만 주어져서는 `server list` 정보를 초기화할 수 없습니다. 따라서 이미 만들어진 `server list` 인자가 필요합니다.

**Comment by SuhwanJang** [comment]
@uhm0311 
> server list 정보를 초기화 하는 곳이 arcus 모듈의 do_arcus_zk_update_cachelist() 함수입니다. zookeeper 통신으로 데이터를 가져와야 하며 master_mc만 주어져서는 server list 정보를 초기화할 수 없습니다. 따라서 이미 만들어진 server list 인자가 필요합니다.

server list 는 master_mc 의 servers 필드로도 가져올 수 있긴 합니다.

**Comment by jhpark816** [comment]
@SuhwanJang 맞습니다.

@uhm0311 
아래와 같이 기능은 동일하지만 2개의 다른 함수를 생각해 볼 수 있어요.
첫째 인자로 주어진 mc에서 cachelist를 update하는 함수인데,
serverifo list을 받아 update하거나 master_mc 포인터를 받아 update할 수 있을 것입니다.

- `memcached_update_cachelist(memcached_st *mc, serverinfo, servercount)`
- `memcached_update_cachelist(memcached_st *mc, master_mc)`

아마 구현 로직의 효율성은 비슷하지 않나 생각되는 데요.
위의 첫째 함수만 두든 2개 함수를 모두 두든 적절한 형태를 판단하여 진행 바랍니다.

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus_priv.h#L110-L121

`master_mc->servers`에서 두 멤버변수 `hostname`, `port`는 가져올 수 있다는 것은 확인했습니다. 다른 멤버변수는 가져올 수 없는 것으로 보이는데, 제가 찾지 못한 방법이 있을까요?

**Comment by SuhwanJang** [comment]
@uhm0311  
replication 의 경우 group list 정보는 rgroups 필드에 있습니다.

**Comment by uhm0311** [comment]
@jhpark816 @SuhwanJang 
`ENABLE_REPLICATION` 여부에 따라 `master_mc->rgroups` 혹은 `master_mc->servers`를 참조하여 server list 초기화 가능한 점 확인했습니다. 감사합니다.

현재 검토 중인 작업 방향은 다음과 같습니다.

1. `memcached` 모듈에 `memcached_return_t memcached_update_cachelist(memcached_st *mc, struct memcached_server_info *serverinfo, uint32_t servercount)` 함수 추가
2. `memcached_update_cachelist()` 함수 내부 구현을 위해 `arcus` 모듈의 `__do_arcus_update_grouplist()` 함수와 `__do_arcus_update_cachelist()` 함수를 `memcached` 모듈의 `__do_memcached_update_grouplist()` 함수와 `__do_memcached_update_cachelist()` 함수로 이동
3. 기존 `arcus` 모듈에서 `__do_arcus_update_grouplist()` 함수와 `__do_arcus_update_cachelist()` 함수를 호출하는 부분을 `memcached` 모듈의 `memcached_update_cachelist()` 함수로 변경
4. `pool` 모듈에 `memcached_return_t memcached_pool_update_cachelist(memcached_pool_st *pool)` 함수 추가
5. 기존 `memcached_pool_repopulate()` 함수 호출하던 곳에서 `memcached_pool_update_cachelist()` 함수를 대신 호출하도록 변경

해당 방향으로 작업 진행하려고 합니다. 작업 방향 검토 부탁드립니다.

**Comment by jhpark816** [comment]
@uhm0311 OK. 확인했고, 진행하시죠.

**Comment by uhm0311** [comment]
@jhpark816 

- 구현 후 테스트 도중 `arcus_pool_connect()` 함수를 수행할 때도 `memcached_pool_update_cachelist()` 함수를 호출하고, `arcus_zk_manager_thread_main()` 함수를 수행할 때도 `do_arcus_zk_watch_and_update_cachelist()` -> `do_arcus_zk_update_cachelist()` -> `do_arcus_update_cachelist()` -> `memcached_pool_update_cachelist()` 함수를 호출하여 테스트 프로그램 실행 시 총 2번 `memcached_pool_update_cachelist()` 함수가 호출되는 현상을 발견했습니다. 
- 로그를 분석해보니 `arcus_zk_manager_thread_main()` 함수에서 먼저 호출하고 그 다음 `arcus_pool_connect()` 함수에서 호출하는 것으로 보여 `arcus_pool_connect()` 함수 안에서 `memcached_pool_update_cachelist()` 함수 호출을 주석 처리 했는데 테스트 프로그램이 정상적으로 동작했습니다. 해당 현상 이슈로 올릴까요?
- 테스트 프로그램은 `multi_threaded`를 오랜 시간 실행되도록 수정한 프로그램입니다.

**Comment by jhpark816** [comment]
@uhm0311 
개선할 필요가 있는 것 같으니, 이슈로 올려두시죠.

**Comment by uhm0311** [comment]
@jhpark816 

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/arcus.cc#L295-L301

- MacOS 환경에서 `arcus/multi_process.c` 소스 코드 참고하여 멀티 프로세스 환경 테스트를 하려고 했는데, 위 코드 부분에서 errno=9 (Bad file descriptor) 에러가 발생했습니다. CentOS 환경에서는 정상적으로 동작하는 것 확인했습니다.
- MacOS 환경에서 300번 라인의 `MAP_SHARED`를 `MAP_SHARED | MAP_ANONYMOUS`로 수정했을 때 프로그램이 정상적으로 동작했습니다. 
- 해당 현상 이슈로 올릴까요?

**Comment by jhpark816** [comment]
@uhm0311 
OK.
- 이슈로 올리고, 왜 그런지 조사 부탁해요.

**Comment by jhpark816** [comment]
@uhm0311 @SuhwanJang 
위의 코멘트 내용을 보니, 아래와 같이 생각됩니다.
- fd가 -1입니다.
   - 특정 file contents를 mmap 시키는 것이 아니라 anonymous memory page를 mmap 시키는 것이네요.
   - 따라서, MAP_ANONYMOUS flag가 필요한 것으로 보입니다.
   - MAP_ANONYMOUS flag가 없다면, -1을 가진 fd가 정상적인 fd이어야 하는 데, 그렇지 않아서 오류를 발생하는 것으로 보입니다.
- 그러면, 예전에는 왜 이 문제가 발생하지 않았을까요?
  - MAP_ANONYMOUS flag가 특정 kernel 버전 이후에 나오지 않았나 생각합니다.
  - 따라서, MAP_ANONYMOUS flag가 지원되기 이전에서 fd 값을 보고 anonymous page 사용한 것으로 보입니다.

**Comment by uhm0311** [comment]
commit: https://github.com/naver/arcus-c-client/commit/f044305e2db7598eab2a6d7cc34c13af5229785b

- 기존 ZK에 의해 server list 업데이트 시 이를 pool에 반영할 때 pool->mc 객체들을 지우고 다시 master의 클론으로 생성하는 방식을 사용했습니다.
- 이러한 연산은 불필요한 메모리 할당과 해제가 계속 일어나 리소스를 낭비하는 것으로 판단 됩니다.
- pool->mc 객체들은 모두 같은 server list를 갖고 있으므로 이를 master의 server list와 1회만 비교한 후 그 차이점을 pool->mc 객체들에 적용하는 로직을 구성했습니다.
