### ISSUE TITLE
[TEST] piped 연산의 유닛 테스트 추가 

### ISSUE THREAD

**Issue by computerphilosopher** [naver/arcus-c-client#89]
파이프 연산시, 응답으로 PIPE_ERROR와 CLIENT_ERROR를 리턴하는 케이스에 대한 테스트 코드를 추가한다.

- PIPE_ERROR bad error or PIPE_ERROR command overflow
  - 둘 다 추가하는 것이 쉬우면, 둘 다 추가하였으면 함.
- CLIENT_ERROR

**Comment by jhpark816** [comment]
@computerphilosopher 이 작업도 진행합시다.

**Comment by jhpark816** [comment]
@computerphilosopher 본 이슈 처리는 완료된 상태인가요 ?

**Comment by computerphilosopher** [comment]
https://github.com/naver/arcus-c-client/pull/106

이 PR로 bad error만 추가되었습니다.

**Comment by jhpark816** [comment]
그러면, 잔여 작업은 무엇인가요 ?

**Comment by computerphilosopher** [comment]
파이프 연산시 다음의 응답을 하는 테스트 코드를 추가해야 합니다.

- PIPE_ERROR command overflow
- CLIENT_ERROR

**Comment by jhpark816** [comment]
@computerphilosopher 우선순위가 낮아 잠시 보류해 둘게요.

**Comment by uhm0311** [comment]
@jhpark816 
`PIPE_ERROR command overflow` 오류는 내부 로직에서 미리 걸러져 실제로 발생하지 않습니다.

https://github.com/naver/arcus-c-client/blob/71bcafd30601dbbc687652fff6a34aa25ca47660/libmemcached/collection.cc#L2985-L2990

위 코드의 `requested_items == MEMCACHED_COLL_MAX_PIPED_CMD_SIZE` 부분이 최대 파이프 커맨드 개수를 조절해 주기 때문에 `PIPE_ERROR command overflow` 오류가 발생하지 않습니다. 위 코드를 아래와 같이 수정하면 `PIPE_ERROR command overflow` 오류가 발생합니다.

```cpp
 if ((i+1) == number_of_piped_items) { 
   ptr->flags.piped= false; /* the end of piped operation */ 
 } else { 
   ptr->flags.piped= true; 
 } 
```

아래와 같은 방법도 실험해 보았으나 `PIPE_ERROR command overflow` 오류가 발생하지 않습니다.

```cpp
#ifdef MEMCACHED_COLL_MAX_PIPED_CMD_SIZE
#undef MEMCACHED_COLL_MAX_PIPED_CMD_SIZE
#define MEMCACHED_COLL_MAX_PIPED_CMD_SIZE 5000
#endif
```

**Comment by jhpark816** [comment]
@uhm0311 
- MEMCACHED_COLL_MAX_PIPED_CMD_SIZE 값을 500 => 5000으로 늘리면, `PIPE_ERROR command overflow` 오류가 발생해야 합니다. 오류가 발생하는 않는 이유를 확인해 보세요.
- C client 구현에서 500개 초과 commands를 보낼 수가 없으니, `PIPE_ERROR command overflow` 응답이 오게 하는 unit test 생성은 불가능하네요. 생략합시다.
- CLIENT_ERROR 오류의 unit test만 추가하면 되는 데, 이건  `PIPE_ERROR bad error` 응답이 오는 경우와 동일하지 않나요? 동일하다면, 이 경우 또한 생략해도 됩니다.

**Comment by uhm0311** [comment]
@jhpark816 

- 이미 빌드 된 `arcus-c-client` 바깥에서 `MEMCACHED_COLL_MAX_PIPED_CMD_SIZE` 값을 바꾸어도 `arcus-c-client` 안에서는 이미 컴파일 시점에 값이 `500`으로 정해져 있으므로 오류가 발생하지 않는 것이었습니다. `arcus-c-lient` 안에서 `MEMCACHED_COLL_MAX_PIPED_CMD_SIZE` 값을 `5000`으로 바꾸고 빌드한 뒤 실행하면 `PIPE_ERROR command overflow`가 정상적으로 발생합니다.
- `arcus-memcached` 소스 코드를 확인한 결과, [`PIPE_ERROR command overflow` 에러와 `PIPE_ERROR memory overflow`를 제외한 파이프 연산 에러는 모두 `PIPE_ERROR bad error`로 처리](https://github.com/naver/arcus-memcached/blob/debf41c797e0591f1a2e56e6c1611fe18d928d55/memcached.c#L1500-L1509)하고 있습니다. `CLIENT_ERROR` 오류도 `PIPE_ERROR bad error`로 처리될 것 같습니다.

**Comment by jhpark816** [comment]
@uhm0311 
`PIPE_ERROR bad error` 오류의 unit test는 추가한 상태이고,
그 외 PIPE_ERROR에 대해서는 unit test 추가하지 않도록 합시다.
